/**
 * 统一应用图标组件 - 后台管理系统使用
 *
 * 使用 iconfont 字体实现所有图标
 * 与小程序和终端预览器保持一致
 *
 * 使用方式：
 * import { AppIcon } from '@/components/ui/icon-picker'
 * <AppIcon name="shield" size={24} className="text-emerald-500" />
 */

import { forwardRef } from 'react'
import type { IconName } from '@/shared/types/icon'
import { cn } from '@/lib/utils'
import '@/shared/assets/iconfont/iconfont.css'

export interface AppIconProps {
  /** 图标名称，必须是 iconfont 中定义的名称 */
  name: IconName
  /** 图标大小（单位：px），默认 24 */
  size?: number
  /** 图标颜色，默认 currentColor */
  color?: string
  /** 额外的 CSS 类名 */
  className?: string
  /** 内联样式 */
  style?: React.CSSProperties
}

/**
 * 应用图标组件
 *
 * 使用 iconfont 字体渲染，确保全平台一致性
 */
export const AppIcon = forwardRef<HTMLElement, AppIconProps>(function AppIcon(
  { name, size = 24, color, className, style },
  ref
) {
  return (
    <i
      ref={ref}
      className={cn(`iconfont icon-${name}`, className)}
      style={{
        fontSize: size,
        color: color,
        lineHeight: 1,
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontStyle: 'normal',
        ...style,
      }}
      aria-hidden="true"
    />
  )
})

/**
 * 推荐的常用图标列表（用于图标选择器）
 * 按分类组织，方便选择
 * 共775个图标可用
 */
export const recommendedIcons: { category: string; icons: { name: IconName; label: string }[] }[] = [
  {
    category: '医疗健康',
    icons: [
      { name: 'stethoscope', label: '听诊器' },
      { name: 'hospital', label: '医院' },
      { name: 'hospital-bed', label: '病床' },
      { name: 'hospital-three', label: '医院3' },
      { name: 'hospital-four', label: '医院4' },
      { name: 'pill', label: '药丸' },
      { name: 'pills', label: '药片' },
      { name: 'injection', label: '注射' },
      { name: 'infusion', label: '输液' },
      { name: 'first-aid-kit', label: '急救箱' },
      { name: 'first-aid-kit-line', label: '急救箱线框' },
      { name: 'medical-box', label: '医疗箱' },
      { name: 'medicine-chest', label: '药箱' },
      { name: 'medicine-bottle', label: '药瓶' },
      { name: 'medicine-bottle-one', label: '药瓶1' },
      { name: 'heartbeat', label: '心跳' },
      { name: 'heart-rate', label: '心率' },
      { name: 'thermometer', label: '温度计' },
      { name: 'thermometer-one', label: '体温计' },
      { name: 'ambulance', label: '救护车' },
      { name: 'sharpicons_ambulance', label: '救护车2' },
      { name: 'ecg', label: '心电图' },
      { name: 'cardioelectric', label: '心电' },
      { name: 'brain', label: '大脑' },
      { name: 'lung', label: '肺' },
      { name: 'teeth', label: '牙齿' },
      { name: 'eyes', label: '眼睛' },
      { name: 'skull', label: '头骨' },
      { name: 'nurse-cap', label: '护士帽' },
      { name: 'prescription', label: '处方' },
      { name: 'medical-files', label: '病历' },
      { name: 'medical-mark', label: '医疗标志' },
      { name: 'red-cross', label: '红十字' },
      { name: 'sharpicons_medical-sign', label: '医疗符号' },
      { name: 'mask', label: '口罩' },
      { name: 'mask-one', label: '口罩1' },
      { name: 'facial-mask', label: '面膜' },
      { name: 'gauze', label: '纱布' },
      { name: 'Patch', label: '创可贴' },
      { name: 'test-tube', label: '试管' },
      { name: 'microscope', label: '显微镜' },
      { name: 'experiment', label: '实验' },
      { name: 'experiment-one', label: '实验1' },
      { name: 'germs', label: '细菌' },
      { name: 'sperm', label: '精子' },
      { name: 'needle', label: '针头' },
      { name: 'nasal', label: '鼻腔' },
      { name: 'abdominal', label: '腹部' },
      { name: 'chest', label: '胸部' },
      { name: 'renal', label: '肾脏' },
      { name: 'uterus', label: '子宫' },
      { name: 'gastrointestinal', label: '胃肠' },
      { name: 'orthopedic', label: '骨科' },
      { name: 'endocrine', label: '内分泌' },
      { name: 'neural', label: '神经' },
      { name: 'plastic-surgery', label: '整形' },
      { name: 'pregnant-women', label: '孕妇' },
      { name: 'nmr', label: '核磁' },
      { name: 'eeg', label: '脑电图' },
      { name: 'detection', label: '检测' },
      { name: 'nutrition', label: '营养' },
      { name: 'medication-time', label: '服药时间' },
      { name: 'traditional-chinese-medicine', label: '中药' },
      { name: 'radiation', label: '放射' },
      { name: 'toxins', label: '毒素' },
      { name: 'harm', label: '有害' },
      { name: 'love-and-help', label: '爱心帮助' },
      { name: 'cross-society', label: '红十字会' },
    ],
  },
  {
    category: '安全保障',
    icons: [
      { name: 'shield', label: '盾牌' },
      { name: 'shield-add', label: '盾牌+' },
      { name: 'lock', label: '锁' },
      { name: 'lock-one', label: '锁1' },
      { name: 'unlock-one', label: '解锁' },
      { name: 'key', label: '钥匙' },
      { name: 'keyhole', label: '锁孔' },
      { name: 'protection', label: '保护' },
      { name: 'protect', label: '保护2' },
      { name: 'security', label: '安全' },
      { name: 'safe-retrieval', label: '安全检索' },
      { name: 'permissions', label: '权限' },
      { name: 'email-security', label: '邮件安全' },
      { name: 'folder-protection', label: '文件夹保护' },
      { name: 'folder-lock', label: '文件夹锁' },
      { name: 'database-lock', label: '数据库锁' },
      { name: 'fire-extinguisher', label: '灭火器' },
      { name: 'umbrella', label: '雨伞' },
      { name: 'umbrella-one', label: '雨伞1' },
      { name: 'umbrella-two', label: '雨伞2' },
    ],
  },
  {
    category: '状态标识',
    icons: [
      { name: 'check', label: '对勾' },
      { name: 'check-one', label: '对勾圆' },
      { name: 'check-small', label: '小对勾' },
      { name: 'success', label: '成功' },
      { name: 'check-correct', label: '正确' },
      { name: 'done-all', label: '全部完成' },
      { name: 'close', label: '关闭' },
      { name: 'close-one', label: '关闭圆' },
      { name: 'close-small', label: '小关闭' },
      { name: 'caution', label: '警告' },
      { name: 'alarm', label: '警报' },
      { name: 'info', label: '信息' },
      { name: 'help', label: '帮助' },
      { name: 'tips', label: '提示' },
      { name: 'tips-one', label: '提示1' },
      { name: 'abnormal', label: '异常' },
      { name: 'forbid', label: '禁止' },
      { name: 'good-one', label: '好1' },
      { name: 'good-two', label: '好2' },
      { name: 'bad-one', label: '差1' },
      { name: 'bad-two', label: '差2' },
      { name: 'loading-one', label: '加载1' },
      { name: 'loading-two', label: '加载2' },
      { name: 'loading-four', label: '加载4' },
    ],
  },
  {
    category: '点赞收藏',
    icons: [
      { name: 'like', label: '点赞' },
      { name: 'dislike', label: '踩' },
      { name: 'dislike-two', label: '踩2' },
      { name: 'heart', label: '爱心' },
      { name: 'Heart', label: '红心' },
      { name: 'Hearts', label: '双心' },
      { name: 'stopwatch-start', label: '星星' },
      { name: 'attention', label: '关注' },
      { name: 'bookmark', label: '书签' },
      { name: 'bookmark-three', label: '书签3' },
      { name: 'collect-picture', label: '收藏图片' },
      { name: 'collection-files', label: '收藏文件' },
      { name: 'personal-collection', label: '个人收藏' },
      { name: 'weixin-favorites', label: '微信收藏' },
    ],
  },
  {
    category: '金融支付',
    icons: [
      { name: 'wallet', label: '钱包' },
      { name: 'wallet-one', label: '钱包1' },
      { name: 'wallet-three', label: '钱包3' },
      { name: 'bank', label: '银行' },
      { name: 'bank-card-one', label: '银行卡' },
      { name: 'paper-money', label: '纸币' },
      { name: 'paper-money-two', label: '纸币2' },
      { name: 'currency', label: '货币' },
      { name: 'financing', label: '金融' },
      { name: 'financing-one', label: '金融1' },
      { name: 'financing-two', label: '金融2' },
      { name: 'finance', label: '财务' },
      { name: 'funds', label: '基金' },
      { name: 'stock-market', label: '股票' },
      { name: 'ipo', label: 'IPO' },
      { name: 'coupon', label: '优惠券' },
      { name: 'gift', label: '礼物' },
      { name: 'gift-bag', label: '礼袋' },
      { name: 'red-envelope', label: '红包' },
      { name: 'credit', label: '信用' },
      { name: 'bill', label: '账单' },
      { name: 'deposit', label: '存款' },
      { name: 'income', label: '收入' },
      { name: 'income-one', label: '收入1' },
      { name: 'expenses', label: '支出' },
      { name: 'consume', label: '消费' },
      { name: 'transaction', label: '交易' },
      { name: 'bank-transfer', label: '转账' },
      { name: 'flash-payment', label: '闪付' },
      { name: 'pay-code-one', label: '付款码1' },
      { name: 'pay-code-two', label: '付款码2' },
      { name: 'payment-method', label: '支付方式' },
      { name: 'alipay', label: '支付宝' },
      { name: 'insert-card', label: '插卡' },
      { name: 'scan-code', label: '扫码' },
      { name: 'two-dimensional-code', label: '二维码' },
      { name: 'two-dimensional-code-one', label: '二维码1' },
      { name: 'two-dimensional-code-two', label: '二维码2' },
      { name: 'percentage', label: '百分比' },
      { name: 'diamond', label: '钻石' },
      { name: 'diamond-ring', label: '钻戒' },
      { name: 'diamond-necklace', label: '项链' },
    ],
  },
  {
    category: '时间日期',
    icons: [
      { name: 'time', label: '时间' },
      { name: 'alarm-clock', label: '闹钟' },
      { name: 'history', label: '历史' },
      { name: 'history-query', label: '历史查询' },
      { name: 'hourglass', label: '沙漏' },
      { name: 'hourglass-full', label: '沙漏满' },
      { name: 'hourglass-null', label: '沙漏空' },
      { name: 'stopwatch-start', label: '秒表' },
      { name: 'date-comes-back', label: '日期' },
      { name: 'watch', label: '手表' },
      { name: 'appointment', label: '预约' },
      { name: 'follow-up-date-sort', label: '日期排序' },
      { name: 'period', label: '周期' },
    ],
  },
  {
    category: '用户相关',
    icons: [
      { name: 'user', label: '用户' },
      { name: 'peoples', label: '用户组' },
      { name: 'people', label: '人物' },
      { name: 'people-safe', label: '安全用户' },
      { name: 'people-safe-one', label: '安全用户1' },
      { name: 'people-plus', label: '添加用户' },
      { name: 'people-plus-one', label: '添加用户1' },
      { name: 'people-minus', label: '删除用户' },
      { name: 'people-minus-one', label: '删除用户1' },
      { name: 'people-delete', label: '移除用户' },
      { name: 'people-delete-one', label: '移除用户1' },
      { name: 'people-search', label: '搜索用户' },
      { name: 'people-search-one', label: '搜索用户1' },
      { name: 'people-download', label: '下载用户' },
      { name: 'people-upload', label: '上传用户' },
      { name: 'people-left', label: '左侧用户' },
      { name: 'people-right', label: '右侧用户' },
      { name: 'people-top', label: '顶部用户' },
      { name: 'people-bottom', label: '底部用户' },
      { name: 'people-top-card', label: '顶部卡片' },
      { name: 'people-bottom-card', label: '底部卡片' },
      { name: 'add-user', label: '添加用户2' },
      { name: 'right-user', label: '正确用户' },
      { name: 'wrong-user', label: '错误用户' },
      { name: 'every-user', label: '所有用户' },
      { name: 'user-folder', label: '用户文件夹' },
      { name: 'user-positioning', label: '用户定位' },
      { name: 'user-to-user-transmission', label: '用户传输' },
      { name: 'avatar', label: '头像' },
      { name: 'vip-one', label: 'VIP' },
      { name: 'medal-one', label: '勋章' },
      { name: 'me', label: '我的' },
      { name: 'personal-privacy', label: '个人隐私' },
      { name: 'id-card-h', label: '身份证横' },
      { name: 'id-card-v', label: '身份证竖' },
      { name: 'passport', label: '护照' },
      { name: 'face-recognition', label: '人脸识别' },
      { name: 'ios-face-recognition', label: 'iOS人脸' },
      { name: 'family', label: '家庭' },
      { name: 'female', label: '女性' },
      { name: 'woman', label: '女人' },
      { name: 'women', label: '女士' },
      { name: 'boy', label: '男孩' },
      { name: 'boy-two', label: '男孩2' },
      { name: 'girl-one', label: '女孩1' },
      { name: 'girl-two', label: '女孩2' },
      { name: 'baby', label: '婴儿' },
      { name: 'baby-one', label: '婴儿1' },
      { name: 'child-with-pacifier', label: '奶嘴婴儿' },
    ],
  },
  {
    category: '通讯联系',
    icons: [
      { name: 'phone-telephone', label: '电话' },
      { name: 'phone-incoming', label: '来电' },
      { name: 'phone-missed', label: '未接' },
      { name: 'comment', label: '评论' },
      { name: 'comment-one', label: '消息' },
      { name: 'comments', label: '多条消息' },
      { name: 'remind', label: '提醒' },
      { name: 'remind-disable', label: '提醒关闭' },
      { name: 'mail', label: '邮件' },
      { name: 'mail-review', label: '邮件审核' },
      { name: 'mail-unpacking', label: '邮件拆封' },
      { name: 'envelope-one', label: '信封' },
      { name: 'email-block', label: '邮件拦截' },
      { name: 'email-delect', label: '邮件删除' },
      { name: 'email-down', label: '邮件下载' },
      { name: 'email-fail', label: '邮件失败' },
      { name: 'email-lock', label: '邮件锁定' },
      { name: 'email-push', label: '邮件推送' },
      { name: 'email-search', label: '邮件搜索' },
      { name: 'email-successfully', label: '邮件成功' },
      { name: 'send-email', label: '发送邮件' },
      { name: 'headset', label: '耳机' },
      { name: 'headset-one', label: '耳机1' },
      { name: 'voicemail', label: '语音信箱' },
      { name: 'text-message', label: '短信' },
      { name: 'message-emoji', label: '表情消息' },
      { name: 'announcement', label: '公告' },
      { name: 'at-sign', label: '@符号' },
    ],
  },
  {
    category: '购物订单',
    icons: [
      { name: 'shopping-cart-one', label: '购物车' },
      { name: 'shopping-cart-two', label: '购物车2' },
      { name: 'shopping-cart-add', label: '加入购物车' },
      { name: 'shopping-bag', label: '购物袋' },
      { name: 'shopping-bag-one', label: '购物袋1' },
      { name: 'shopping', label: '购物' },
      { name: 'mall-bag', label: '商场购物袋' },
      { name: 'the-single-shoulder-bag', label: '单肩包' },
      { name: 'commodity', label: '商品' },
      { name: 'transaction-order', label: '订单' },
      { name: 'checklist', label: '清单' },
      { name: 'list-success', label: '清单成功' },
      { name: 'buy', label: '购买' },
      { name: 'receive', label: '收货' },
      { name: 'ticket-one', label: '票券' },
      { name: 'label', label: '标签' },
      { name: 'box', label: '盒子' },
      { name: 'trunk', label: '行李箱' },
    ],
  },
  {
    category: '文件文档',
    icons: [
      { name: 'folder', label: '文件夹' },
      { name: 'folder-close', label: '文件夹关闭' },
      { name: 'folder-plus', label: '文件夹添加' },
      { name: 'folder-download', label: '文件夹下载' },
      { name: 'folder-upload', label: '文件夹上传' },
      { name: 'folder-code', label: '代码文件夹' },
      { name: 'folder-code-one', label: '代码文件夹1' },
      { name: 'folder-failed', label: '文件夹失败' },
      { name: 'folder-focus', label: '文件夹关注' },
      { name: 'folder-focus-one', label: '文件夹关注1' },
      { name: 'folder-music-one', label: '音乐文件夹' },
      { name: 'seo-folder', label: 'SEO文件夹' },
      { name: 'document-folder', label: '文档文件夹' },
      { name: 'file-addition', label: '添加文件' },
      { name: 'file-addition-one', label: '添加文件1' },
      { name: 'file-code', label: '代码文件' },
      { name: 'file-code-one', label: '代码文件1' },
      { name: 'file-collection', label: '收藏文件' },
      { name: 'file-collection-one', label: '收藏文件1' },
      { name: 'file-conversion', label: '转换文件' },
      { name: 'file-conversion-one', label: '转换文件1' },
      { name: 'file-date', label: '日期文件' },
      { name: 'file-date-one', label: '日期文件1' },
      { name: 'file-display-one', label: '展示文件' },
      { name: 'file-doc', label: 'DOC文件' },
      { name: 'file-excel', label: 'Excel文件' },
      { name: 'file-pdf-one', label: 'PDF文件' },
      { name: 'file-word', label: 'Word文件' },
      { name: 'file-zip', label: 'Zip文件' },
      { name: 'file-editing', label: '编辑文件' },
      { name: 'file-failed', label: '失败文件' },
      { name: 'file-failed-one', label: '失败文件1' },
      { name: 'file-focus', label: '关注文件' },
      { name: 'file-focus-one', label: '关注文件1' },
      { name: 'file-hash', label: '哈希文件' },
      { name: 'file-hiding', label: '隐藏文件' },
      { name: 'file-search', label: '搜索文件' },
      { name: 'file-search-one', label: '搜索文件1' },
      { name: 'file-search-two', label: '搜索文件2' },
      { name: 'file-settings-one', label: '设置文件' },
      { name: 'file-staff', label: '员工文件' },
      { name: 'file-success', label: '成功文件' },
      { name: 'file-success-one', label: '成功文件1' },
      { name: 'file-text', label: '文本文件' },
      { name: 'file-tips', label: '提示文件' },
      { name: 'file-withdrawal-one', label: '撤回文件' },
      { name: 'data-file', label: '数据文件' },
      { name: 'audio-file', label: '音频文件' },
      { name: 'video-file', label: '视频文件' },
      { name: 'termination-file', label: '终止文件' },
      { name: 'clipboard', label: '剪贴板' },
      { name: 'doc-add', label: '添加文档' },
      { name: 'doc-fail', label: '失败文档' },
      { name: 'doc-search', label: '搜索文档' },
      { name: 'report', label: '报告' },
      { name: 'agreement', label: '协议' },
      { name: 'copyright', label: '版权' },
      { name: 'trademark', label: '商标' },
      { name: 'paperclip', label: '回形针' },
      { name: 'zip', label: '压缩' },
      { name: 'excel', label: 'Excel' },
      { name: 'word', label: 'Word' },
      { name: 'ppt', label: 'PPT' },
    ],
  },
  {
    category: '箭头方向',
    icons: [
      { name: 'arrow-up', label: '向上箭头' },
      { name: 'arrow-down', label: '向下箭头' },
      { name: 'arrow-circle-up', label: '圆形向上' },
      { name: 'arrow-circle-down', label: '圆形向下' },
      { name: 'arrow-circle-left', label: '圆形向左' },
      { name: 'arrow-circle-right', label: '圆形向右' },
      { name: 'up', label: '上' },
      { name: 'down', label: '下' },
      { name: 'left', label: '左' },
      { name: 'right', label: '右' },
      { name: 'up-c', label: '上C' },
      { name: 'down-c', label: '下C' },
      { name: 'back', label: '返回' },
      { name: 'return', label: '返回2' },
      { name: 'go-ahead', label: '前进' },
      { name: 'to-top-one', label: '置顶' },
      { name: 'to-bottom-one', label: '置底' },
      { name: 'circle-double-up', label: '双向上' },
      { name: 'circle-double-down', label: '双向下' },
      { name: 'circle-double-left', label: '双向左' },
      { name: 'circle-double-right', label: '双向右' },
      { name: 'trending-up', label: '上升趋势' },
      { name: 'trending-down', label: '下降趋势' },
      { name: 'exchange', label: '交换' },
      { name: 'exchange-two', label: '交换2' },
      { name: 'exchange-three', label: '交换3' },
      { name: 'exchange-four', label: '交换4' },
      { name: 'data-switching', label: '数据切换' },
      { name: 'transform', label: '转换' },
      { name: 'rotate-one', label: '旋转' },
      { name: 'reverse-rotation', label: '反转' },
      { name: 'undo', label: '撤销' },
      { name: 'turn-around', label: '掉头' },
      { name: 'refresh', label: '刷新' },
      { name: 'swipe', label: '滑动' },
      { name: 'cycle-movement', label: '循环' },
    ],
  },
  {
    category: '多媒体',
    icons: [
      { name: 'camera', label: '相机' },
      { name: 'pic', label: '图片' },
      { name: 'picture', label: '图片2' },
      { name: 'picture-one', label: '图片1' },
      { name: 'add-pic', label: '添加图片' },
      { name: 'add-picture', label: '添加图片2' },
      { name: 'new-picture', label: '新图片' },
      { name: 'success-picture', label: '成功图片' },
      { name: 'fail-picture', label: '失败图片' },
      { name: 'error-picture', label: '错误图片' },
      { name: 'disabled-picture', label: '禁用图片' },
      { name: 'down-picture', label: '下载图片' },
      { name: 'upload-picture', label: '上传图片' },
      { name: 'moving-picture', label: '动图' },
      { name: 'video', label: '视频' },
      { name: 'video-one', label: '视频1' },
      { name: 'carousel-video', label: '轮播视频' },
      { name: 'video-conference', label: '视频会议' },
      { name: 'film', label: '电影' },
      { name: 'play', label: '播放' },
      { name: 'play-one', label: '播放1' },
      { name: 'play-two', label: '播放2' },
      { name: 'play-cycle', label: '循环播放' },
      { name: 'pause', label: '暂停' },
      { name: 'pause-one', label: '暂停1' },
      { name: 'music', label: '音乐' },
      { name: 'music-cd', label: '音乐CD' },
      { name: 'music-list', label: '音乐列表' },
      { name: 'music-rhythm', label: '音乐节奏' },
      { name: 'voice', label: '语音' },
      { name: 'voice-one', label: '语音1' },
      { name: 'volume-up', label: '音量增' },
      { name: 'volume-down', label: '音量减' },
      { name: 'volume-small', label: '小音量' },
      { name: 'volume-notice', label: '音量提示' },
      { name: 'volume-mute', label: '静音' },
      { name: 'mute', label: '静音2' },
      { name: 'fm', label: 'FM' },
    ],
  },
  {
    category: '界面操作',
    icons: [
      { name: 'home', label: '首页' },
      { name: 'setting', label: '设置' },
      { name: 'setting-one', label: '设置1' },
      { name: 'setting-three', label: '设置3' },
      { name: 'setting-config', label: '配置设置' },
      { name: 'config', label: '配置' },
      { name: 'search', label: '搜索' },
      { name: 'find-one', label: '查找' },
      { name: 'font-search', label: '字体搜索' },
      { name: 'edit', label: '编辑' },
      { name: 'edit-name', label: '编辑名称' },
      { name: 'editing', label: '编辑中' },
      { name: 'editor', label: '编辑器' },
      { name: 'pencil', label: '铅笔' },
      { name: 'delete', label: '删除' },
      { name: 'delete-three', label: '删除3' },
      { name: 'delete-five', label: '删除5' },
      { name: 'delete-mode', label: '删除模式' },
      { name: 'clear', label: '清除' },
      { name: 'add', label: '添加' },
      { name: 'add-one', label: '添加1' },
      { name: 'add-four', label: '添加4' },
      { name: 'add-mode', label: '添加模式' },
      { name: 'plus', label: '加号' },
      { name: 'plus-cross', label: '加号十字' },
      { name: 'reduce', label: '减少' },
      { name: 'reduce-one', label: '减少1' },
      { name: 'share-three', label: '分享' },
      { name: 'download', label: '下载' },
      { name: 'download-four', label: '下载4' },
      { name: 'download-web', label: '网页下载' },
      { name: 'upload-one', label: '上传' },
      { name: 'upload-two', label: '上传2' },
      { name: 'upload-three', label: '上传3' },
      { name: 'upload-logs', label: '上传日志' },
      { name: 'more', label: '更多' },
      { name: 'more-one', label: '更多1' },
      { name: 'more-two', label: '更多2' },
      { name: 'more-app', label: '更多应用' },
      { name: 'copy-one', label: '复制' },
      { name: 'cutting', label: '剪切' },
      { name: 'save', label: '保存' },
      { name: 'send', label: '发送' },
      { name: 'link', label: '链接' },
      { name: 'link-one', label: '链接1' },
      { name: 'link-two', label: '链接2' },
      { name: 'link-three', label: '链接3' },
      { name: 'unlink', label: '取消链接' },
      { name: 'click', label: '点击' },
      { name: 'aiming', label: '瞄准' },
      { name: 'full-screen', label: '全屏' },
      { name: 'full-selection', label: '全选' },
      { name: 'zoom-in', label: '放大' },
      { name: 'zoom-out', label: '缩小' },
      { name: 'preview-open', label: '预览开' },
      { name: 'preview-close-one', label: '预览关' },
      { name: 'viewfinder', label: '取景器' },
      { name: 'optimize', label: '优化' },
      { name: 'filter', label: '筛选' },
      { name: 'sort-one', label: '排序1' },
      { name: 'sort-two', label: '排序2' },
      { name: 'sort-three', label: '排序3' },
      { name: 'sort-four', label: '排序4' },
      { name: 'alphabetical-sorting', label: '字母排序' },
      { name: 'alphabetical-sorting-two', label: '字母排序2' },
    ],
  },
  {
    category: '布局展示',
    icons: [
      { name: 'list', label: '列表' },
      { name: 'list-middle', label: '列表居中' },
      { name: 'list-numbers', label: '数字列表' },
      { name: 'ordered-list', label: '有序列表' },
      { name: 'grid-two', label: '两列网格' },
      { name: 'grid-three', label: '三列网格' },
      { name: 'grid-four', label: '四列网格' },
      { name: 'grid-nine', label: '九宫格' },
      { name: 'grid-sixteen', label: '十六宫格' },
      { name: 'layout-two', label: '布局2' },
      { name: 'layout-four', label: '布局4' },
      { name: 'layout-five', label: '布局5' },
      { name: 'column', label: '列' },
      { name: 'row-height', label: '行高' },
      { name: 'view-grid-detail', label: '网格详情' },
      { name: 'waterfalls-h', label: '瀑布流横' },
      { name: 'waterfalls-v', label: '瀑布流竖' },
      { name: 'hamburger-button', label: '汉堡菜单' },
      { name: 'application-menu', label: '应用菜单' },
      { name: 'all-application', label: '所有应用' },
      { name: 'components', label: '组件' },
      { name: 'layers', label: '图层' },
      { name: 'mindmap-map', label: '思维导图' },
      { name: 'bottom-bar', label: '底栏' },
      { name: 'right-bar', label: '右栏' },
      { name: 'indent-left', label: '左缩进' },
      { name: 'indent-right', label: '右缩进' },
      { name: 'left-alignment', label: '左对齐' },
      { name: 'align-right', label: '右对齐' },
      { name: 'align-top', label: '顶对齐' },
      { name: 'align-bottom', label: '底对齐' },
      { name: 'align-vertically', label: '垂直对齐' },
      { name: 'align-text-top', label: '文字顶对齐' },
      { name: 'align-text-middle', label: '文字居中' },
      { name: 'align-text-bottom', label: '文字底对齐' },
    ],
  },
  {
    category: '数据图表',
    icons: [
      { name: 'analysis', label: '分析' },
      { name: 'market-analysis', label: '市场分析' },
      { name: 'trend', label: '趋势' },
      { name: 'trend-two', label: '趋势2' },
      { name: 'pie', label: '饼图' },
      { name: 'pie-three', label: '饼图3' },
      { name: 'bubble-chart', label: '气泡图' },
      { name: 'performance', label: '性能' },
      { name: 'coordinate-system', label: '坐标系' },
      { name: 'equalizer', label: '均衡器' },
      { name: 'speed', label: '速度' },
      { name: 'scale', label: '刻度' },
      { name: 'level', label: '等级' },
      { name: 'imbalance', label: '失衡' },
      { name: 'balance-two', label: '平衡' },
      { name: 'percentage', label: '百分比' },
      { name: 'division', label: '除法' },
      { name: 'add-subtract', label: '加减' },
    ],
  },
  {
    category: '表情符号',
    icons: [
      { name: 'smiling-face-with-squinting-eyes', label: '微笑' },
      { name: 'grinning-face', label: '咧嘴笑' },
      { name: 'grinning-face-with-squinting-eyes', label: '眯眼笑' },
      { name: 'winking-face', label: '眨眼' },
      { name: 'winking-face-with-open-eyes', label: '眨眼睁眼' },
      { name: 'neutral-face', label: '中性表情' },
      { name: 'frowning-face-whit-open-mouth', label: '皱眉' },
      { name: 'anguished-face', label: '苦恼' },
      { name: 'astonished-face', label: '惊讶' },
      { name: 'surprised-face-with-open-big-mouth', label: '大惊' },
      { name: 'grimacing-face', label: '做鬼脸' },
      { name: 'distraught-face', label: '心烦' },
      { name: 'weary-face', label: '疲惫' },
      { name: 'worried-face', label: '担忧' },
      { name: 'loudly-crying-face-whit-open-mouth', label: '大哭' },
      { name: 'angry-face', label: '生气' },
      { name: 'thinking-problem', label: '思考' },
      { name: 'sleep-one', label: '睡眠' },
    ],
  },
  {
    category: '天气自然',
    icons: [
      { name: 'brightness', label: '亮度' },
      { name: 'sunset', label: '日落' },
      { name: 'fire', label: '火焰' },
      { name: 'lightning', label: '闪电' },
      { name: 'waves', label: '波浪' },
      { name: 'waves-left', label: '左波浪' },
      { name: 'water-rate', label: '水滴' },
      { name: 'water-rate-two', label: '水滴2' },
      { name: 'whirlwind', label: '旋风' },
      { name: 'ripple', label: '涟漪' },
      { name: 'leaf', label: '叶子' },
      { name: 'leaves-one', label: '叶子1' },
      { name: 'four-leaves', label: '四叶草' },
      { name: 'pure-natural', label: '纯天然' },
      { name: 'geometric-flowers', label: '几何花' },
    ],
  },
  {
    category: '动物昆虫',
    icons: [
      { name: 'bird', label: '鸟' },
      { name: 'swallow', label: '燕子' },
      { name: 'pigeon', label: '鸽子' },
      { name: 'bee', label: '蜜蜂' },
      { name: 'butterfly', label: '蝴蝶' },
      { name: 'elephant', label: '大象' },
      { name: 'cattle', label: '牛' },
      { name: 'cattle-zodiac', label: '牛生肖' },
      { name: 'pig', label: '猪' },
    ],
  },
  {
    category: '母婴育儿',
    icons: [
      { name: 'baby', label: '婴儿' },
      { name: 'baby-one', label: '婴儿1' },
      { name: 'baby-app', label: '婴儿APP' },
      { name: 'baby-bottle', label: '奶瓶' },
      { name: 'sippy-cup', label: '吸管杯' },
      { name: 'baby-taste', label: '婴儿口味' },
      { name: 'child-with-pacifier', label: '奶嘴婴儿' },
      { name: 'rocking-horse', label: '摇摇马' },
      { name: 'clothes-diapers', label: '尿布' },
      { name: 'bottle', label: '瓶子' },
    ],
  },
  {
    category: '服饰配件',
    icons: [
      { name: 't-shirt', label: 'T恤' },
      { name: 'sweater', label: '毛衣' },
      { name: 'men-jacket', label: '男夹克' },
      { name: 'women-coat', label: '女外套' },
      { name: 'short-skirt', label: '短裙' },
      { name: 'shorts', label: '短裤' },
      { name: 'swimsuit', label: '泳装' },
      { name: 'panties', label: '内裤' },
      { name: 'high-heeled-shoes', label: '高跟鞋' },
      { name: 'slippers-one', label: '拖鞋' },
      { name: 'glasses-one', label: '眼镜' },
      { name: 'glasses-three', label: '眼镜3' },
      { name: 'three-d-glasses', label: '3D眼镜' },
      { name: 'clothes-gloves', label: '手套' },
      { name: 'watch', label: '手表' },
      { name: 'waistline', label: '腰带' },
      { name: 'perfume', label: '香水' },
      { name: 'beauty', label: '美妆' },
    ],
  },
  {
    category: '运动健身',
    icons: [
      { name: 'fitness', label: '健身' },
      { name: 'dumbbell', label: '哑铃' },
      { name: 'riding', label: '骑行' },
      { name: 'weight', label: '体重' },
      { name: 'game-two', label: '游戏' },
      { name: 'game-ps', label: 'PS游戏' },
      { name: 'entertainment', label: '娱乐' },
    ],
  },
  {
    category: '教育学习',
    icons: [
      { name: 'book', label: '书籍' },
      { name: 'book-one', label: '书籍1' },
      { name: 'book-open', label: '打开的书' },
      { name: 'bookshelf', label: '书架' },
      { name: 'degree-hat', label: '学位帽' },
      { name: 'classroom', label: '教室' },
      { name: 'english', label: '英语' },
      { name: 'translate', label: '翻译' },
      { name: 'translation', label: '翻译2' },
      { name: 'instruction', label: '说明' },
      { name: 'newspaper-folding', label: '报纸' },
    ],
  },
  {
    category: '科技设备',
    icons: [
      { name: 'android', label: '安卓' },
      { name: 'apple', label: '苹果' },
      { name: 'browser-chrome', label: 'Chrome' },
      { name: 'bluetooth', label: '蓝牙' },
      { name: 'battery-full', label: '满电' },
      { name: 'battery-empty', label: '空电' },
      { name: 'battery-charge', label: '充电' },
      { name: 'battery-working', label: '电池工作' },
      { name: 'power', label: '电源' },
      { name: 'monitor-two', label: '显示器' },
      { name: 'terminal', label: '终端' },
      { name: 'web-page', label: '网页' },
      { name: 'add-web', label: '添加网页' },
      { name: 'disabaled-web', label: '禁用网页' },
      { name: 'code', label: '代码' },
      { name: 'code-brackets', label: '代码括号' },
      { name: 'source-code', label: '源代码' },
      { name: 'bug', label: 'Bug' },
      { name: 'system', label: '系统' },
      { name: 'database-first', label: '数据库' },
      { name: 'database-fail', label: '数据库失败' },
      { name: 'blockchain', label: '区块链' },
      { name: 'connect', label: '连接' },
      { name: 'connection-point-two', label: '连接点' },
      { name: 'workbench', label: '工作台' },
      { name: 'figma-component', label: 'Figma组件' },
      { name: 'adobe-illustrate', label: 'AI' },
      { name: 'bytedance-applets', label: '字节小程序' },
      { name: 'bytedance-mini-app', label: '字节小程序2' },
      { name: 'xigua', label: '西瓜' },
      { name: 'youtube', label: 'YouTube' },
    ],
  },
  {
    category: '地图位置',
    icons: [
      { name: 'map-draw', label: '地图' },
      { name: 'discovery-index', label: '发现' },
      { name: 'general-branch', label: '分支' },
      { name: 'left-branch', label: '左分支' },
      { name: 'lower-branch', label: '下分支' },
      { name: 'intersection', label: '交叉' },
      { name: 'adjacent-item', label: '相邻' },
      { name: 'blocks-and-arrows', label: '块和箭头' },
      { name: 'six-circular-connection', label: '六圆连接' },
      { name: 'nests', label: '嵌套' },
    ],
  },
  {
    category: '社交平台',
    icons: [
      { name: 'weixin-market', label: '微信' },
      { name: 'weixin-people-nearby', label: '附近的人' },
      { name: 'topic', label: '话题' },
      { name: 'ad', label: '广告' },
      { name: 'enquire', label: '咨询' },
      { name: 'hands', label: '握手' },
    ],
  },
  {
    category: '形状图形',
    icons: [
      { name: 'circle-five-line', label: '五线圆' },
      { name: 'circles-seven', label: '七圆' },
      { name: 'hexagon-strip', label: '六边形条' },
      { name: 'three-hexagons', label: '三六边形' },
      { name: 'three-triangles', label: '三角形组' },
      { name: 'two-triangles', label: '双三角' },
      { name: 'two-triangles-two', label: '双三角2' },
      { name: 'triangle-round-rectangle', label: '三角圆矩' },
      { name: 'cube-two', label: '立方体' },
      { name: 'composition', label: '组合' },
      { name: 'difference-set', label: '差集' },
    ],
  },
]

/**
 * 获取所有推荐图标的扁平列表
 */
export function getFlatRecommendedIcons(): { name: IconName; label: string; category: string }[] {
  return recommendedIcons.flatMap((group) =>
    group.icons.map((icon) => ({ ...icon, category: group.category }))
  )
}

export type { IconName }
