/**
 * 终端全局预览器子组件导出
 */

export { BrandSection } from './BrandSection'
export { SearchBar } from './SearchBar'
export { CategorySection } from './CategorySection'
export { BannerSection } from './BannerSection'
export { StatsCard } from './StatsCard'
export { ServiceRecommendation } from './ServiceRecommendation'
export { ContentSection } from './ContentSection'
export { FooterSection } from './FooterSection'
export { TabBarNav } from './TabBarNav'
export { ScrollIndicator } from './ScrollIndicator'
export { PhoneFrame } from './PhoneFrame'
export { DebugPanel, shouldShowDebugPanel } from './DebugPanel'
export { EscortLoginDialog } from './EscortLoginDialog'
export { PhoneBindPromptDialog } from './PhoneBindPromptDialog'
export type { PhoneBindPromptDialogProps } from './PhoneBindPromptDialog'
// SmsVerifyDialog 保留供 H5/其他终端使用，小程序使用微信授权
// export { SmsVerifyDialog } from './SmsVerifyDialog'
// export type { SmsVerifyDialogProps } from './SmsVerifyDialog'
export { PermissionPrompt } from './PermissionPrompt'
export { PreviewErrorBoundary } from './PreviewErrorBoundary'
export { ListSkeleton } from './ListSkeleton'
export type { ListSkeletonProps, ListSkeletonVariant } from './ListSkeleton'
export { ErrorRetry } from './ErrorRetry'
export type { ErrorRetryProps } from './ErrorRetry'
export { PageTransition, FadeTransition, getRefreshingClass } from './PageTransition'
export { PatientsPageSkeleton } from './PatientsPageSkeleton'
export type { PatientsPageSkeletonProps } from './PatientsPageSkeleton'
export { UserOrdersPageSkeleton } from './UserOrdersPageSkeleton'
export type { UserOrdersPageSkeletonProps } from './UserOrdersPageSkeleton'
