export interface DepartmentOption {
  id: string
  name: string
  icon: string
}

// 基于《医院科室库.xlsx》科室库抽取，兼容陪诊员擅长科室匹配
export const DEPARTMENT_LIST: DepartmentOption[] = [
  { id: 'd001', name: '普通内科', icon: 'stethoscope' },
  { id: 'd002', name: '普通外科', icon: 'stethoscope' },
  { id: 'd003', name: '妇产科', icon: 'stethoscope' },
  { id: 'd004', name: '呼吸内科', icon: 'stethoscope' },
  { id: 'd005', name: '泌尿外科', icon: 'stethoscope' },
  { id: 'd006', name: '妇科', icon: 'stethoscope' },
  { id: 'd007', name: '心血管内科', icon: 'stethoscope' },
  { id: 'd008', name: '心血管外科', icon: 'stethoscope' },
  { id: 'd009', name: '产科', icon: 'stethoscope' },
  { id: 'd010', name: '消化内科', icon: 'stethoscope' },
  { id: 'd011', name: '肝胆外科', icon: 'stethoscope' },
  { id: 'd012', name: '妇科肿瘤', icon: 'stethoscope' },
  { id: 'd013', name: '神经内科', icon: 'stethoscope' },
  { id: 'd014', name: '神经外科', icon: 'stethoscope' },
  { id: 'd015', name: '计划生育科', icon: 'stethoscope' },
  { id: 'd016', name: '血液内科', icon: 'stethoscope' },
  { id: 'd017', name: '胸外科', icon: 'stethoscope' },
  { id: 'd018', name: '遗传咨询科', icon: 'stethoscope' },
  { id: 'd019', name: '内分泌科', icon: 'stethoscope' },
  { id: 'd020', name: '甲状腺乳腺外科', icon: 'stethoscope' },
  { id: 'd021', name: '妇女保健科', icon: 'stethoscope' },
  { id: 'd022', name: '肾内科', icon: 'stethoscope' },
  { id: 'd023', name: '结直肠科', icon: 'stethoscope' },
  { id: 'd024', name: '妇产科其他', icon: 'stethoscope' },
  { id: 'd025', name: '变态反应科', icon: 'stethoscope' },
  { id: 'd026', name: '整形外科', icon: 'stethoscope' },
  { id: 'd027', name: '风湿免疫科', icon: 'stethoscope' },
  { id: 'd028', name: '烧伤科', icon: 'stethoscope' },
  { id: 'd029', name: '小儿普通科', icon: 'stethoscope' },
  { id: 'd030', name: '老年医学科', icon: 'stethoscope' },
  { id: 'd031', name: '外科其他', icon: 'stethoscope' },
  { id: 'd032', name: '新生儿科', icon: 'stethoscope' },
  { id: 'd033', name: '睡眠科', icon: 'stethoscope' },
  { id: 'd034', name: '胃肠外科', icon: 'stethoscope' },
  { id: 'd035', name: '小儿呼吸科', icon: 'stethoscope' },
  { id: 'd036', name: '感染病科', icon: 'stethoscope' },
  { id: 'd037', name: '肛肠科', icon: 'stethoscope' },
  { id: 'd038', name: '小儿消化科', icon: 'stethoscope' },
  { id: 'd039', name: '内科其他', icon: 'stethoscope' },
  { id: 'd040', name: '小儿神经内科', icon: 'stethoscope' },
  { id: 'd041', name: '心内科', icon: 'stethoscope' },
  { id: 'd042', name: '小儿普通外科', icon: 'stethoscope' },
  { id: 'd043', name: '小儿心脏内科', icon: 'stethoscope' },
  { id: 'd044', name: '小儿眼科', icon: 'stethoscope' },
  { id: 'd045', name: '小儿肾病科', icon: 'stethoscope' },
  { id: 'd046', name: '眼科', icon: 'stethoscope' },
  { id: 'd047', name: '小儿胸外科', icon: 'stethoscope' },
  { id: 'd048', name: '小儿内分泌科', icon: 'stethoscope' },
  { id: 'd049', name: '眼底科', icon: 'stethoscope' },
  { id: 'd050', name: '小儿神经外科', icon: 'stethoscope' },
  { id: 'd051', name: '小儿免疫科', icon: 'stethoscope' },
  { id: 'd052', name: '眼角膜科', icon: 'stethoscope' },
  { id: 'd053', name: '小儿皮肤科', icon: 'stethoscope' },
  { id: 'd054', name: '小儿血液病科', icon: 'stethoscope' },
  { id: 'd055', name: '青光眼科', icon: 'stethoscope' },
  { id: 'd056', name: '小儿泌尿外科', icon: 'stethoscope' },
  { id: 'd057', name: '小儿感染科', icon: 'stethoscope' },
  { id: 'd058', name: '白内障科', icon: 'stethoscope' },
  { id: 'd059', name: '小儿骨科', icon: 'stethoscope' },
  { id: 'd060', name: '小儿遗传病科', icon: 'stethoscope' },
  { id: 'd061', name: '眼外伤科', icon: 'stethoscope' },
  { id: 'd062', name: '小儿耳鼻喉科', icon: 'stethoscope' },
  { id: 'd063', name: '小儿内科其他', icon: 'stethoscope' },
  { id: 'd064', name: '眼肿瘤科', icon: 'stethoscope' },
  { id: 'd065', name: '小儿口腔科', icon: 'stethoscope' },
  { id: 'd066', name: '眼整形科', icon: 'stethoscope' },
  { id: 'd067', name: '小儿外科其他', icon: 'stethoscope' },
  { id: 'd068', name: '耳鼻喉头颈外科', icon: 'stethoscope' },
  { id: 'd069', name: '视光学科', icon: 'stethoscope' },
  { id: 'd070', name: '耳科', icon: 'stethoscope' },
  { id: 'd071', name: '屈光科', icon: 'stethoscope' },
  { id: 'd072', name: '口腔科', icon: 'stethoscope' },
  { id: 'd073', name: '鼻科', icon: 'stethoscope' },
  { id: 'd074', name: '眼科其他', icon: 'stethoscope' },
  { id: 'd075', name: '正畸科', icon: 'stethoscope' },
  { id: 'd076', name: '咽喉科', icon: 'stethoscope' },
  { id: 'd077', name: '牙周科', icon: 'stethoscope' },
  { id: 'd078', name: '骨科', icon: 'stethoscope' },
  { id: 'd079', name: '牙体牙髓科', icon: 'stethoscope' },
  { id: 'd080', name: '肿瘤科', icon: 'stethoscope' },
  { id: 'd081', name: '关节外科', icon: 'stethoscope' },
  { id: 'd082', name: '种植科', icon: 'stethoscope' },
  { id: 'd083', name: '肿瘤内科', icon: 'stethoscope' },
  { id: 'd084', name: '脊椎外科', icon: 'stethoscope' },
  { id: 'd085', name: '口腔黏膜科', icon: 'stethoscope' },
  { id: 'd086', name: '肿瘤外科', icon: 'stethoscope' },
  { id: 'd087', name: '手外科', icon: 'stethoscope' },
  { id: 'd088', name: '颌面外科', icon: 'stethoscope' },
  { id: 'd089', name: '足踝外科', icon: 'stethoscope' },
  { id: 'd090', name: '口腔修复科', icon: 'stethoscope' },
  { id: 'd091', name: '男科', icon: 'stethoscope' },
  { id: 'd092', name: '矫形外科', icon: 'stethoscope' },
  { id: 'd093', name: '口腔预防保健科', icon: 'stethoscope' },
  { id: 'd094', name: '医疗美容科', icon: 'stethoscope' },
  { id: 'd095', name: '创伤骨科', icon: 'stethoscope' },
  { id: 'd096', name: '口腔科其他', icon: 'stethoscope' },
  { id: 'd097', name: '康复医学科', icon: 'stethoscope' },
  { id: 'd098', name: '运动医学科', icon: 'stethoscope' },
  { id: 'd099', name: '理疗科', icon: 'stethoscope' },
  { id: 'd100', name: '骨与软组织肿瘤科', icon: 'stethoscope' },
  { id: 'd101', name: '精神科', icon: 'stethoscope' },
  { id: 'd102', name: '麻醉科', icon: 'stethoscope' },
  { id: 'd103', name: '骨科其他', icon: 'stethoscope' },
  { id: 'd104', name: '心理咨询科', icon: 'stethoscope' },
  { id: 'd105', name: '全科医学科', icon: 'stethoscope' },
  { id: 'd106', name: '药物依赖科', icon: 'stethoscope' },
  { id: 'd107', name: '预防保健科', icon: 'stethoscope' },
  { id: 'd108', name: '儿童心理科', icon: 'stethoscope' },
  { id: 'd109', name: '青少年精神心理科', icon: 'stethoscope' },
  { id: 'd110', name: '疫苗接种科', icon: 'stethoscope' },
  { id: 'd111', name: '儿童保健科', icon: 'stethoscope' },
  { id: 'd112', name: '疼痛科', icon: 'stethoscope' },
  { id: 'd113', name: '儿童康复科', icon: 'stethoscope' },
  { id: 'd114', name: '传染科', icon: 'stethoscope' },
  { id: 'd115', name: '中西医结合科', icon: 'stethoscope' },
  { id: 'd116', name: '儿童营养科', icon: 'stethoscope' },
  { id: 'd117', name: '肝病科', icon: 'stethoscope' },
  { id: 'd118', name: '病理科', icon: 'stethoscope' },
  { id: 'd119', name: '儿童生长发育科', icon: 'stethoscope' },
  { id: 'd120', name: '结核病科', icon: 'stethoscope' },
  { id: 'd121', name: '地方病科', icon: 'stethoscope' },
  { id: 'd122', name: '民族医学科', icon: 'stethoscope' },
  { id: 'd123', name: '发热门诊', icon: 'stethoscope' },
  { id: 'd124', name: '影像科', icon: 'stethoscope' },
  { id: 'd125', name: '职业病科', icon: 'stethoscope' },
  { id: 'd126', name: '肠道门诊', icon: 'stethoscope' },
  { id: 'd127', name: '超声科', icon: 'stethoscope' },
  { id: 'd128', name: '重症医学科', icon: 'stethoscope' },
  { id: 'd129', name: '核医学科', icon: 'stethoscope' },
  { id: 'd130', name: '安宁疗护与关怀科', icon: 'stethoscope' },
  { id: 'd131', name: '中医科', icon: 'stethoscope' },
  { id: 'd132', name: '多学科联合门诊', icon: 'stethoscope' },
  { id: 'd133', name: '中医儿科', icon: 'stethoscope' },
  { id: 'd134', name: '营养咨询门诊', icon: 'stethoscope' },
  { id: 'd135', name: '心身医学科', icon: 'stethoscope' },
  { id: 'd136', name: '中医眼科', icon: 'stethoscope' },
  { id: 'd137', name: '健康管理门诊', icon: 'stethoscope' },
  { id: 'd138', name: '体检中心', icon: 'stethoscope' },
  { id: 'd139', name: '针灸科', icon: 'stethoscope' },
  { id: 'd140', name: '减重门诊', icon: 'stethoscope' },
  { id: 'd141', name: '药剂科', icon: 'stethoscope' },
  { id: 'd142', name: '中医按摩科', icon: 'stethoscope' },
  { id: 'd143', name: '医技科', icon: 'stethoscope' },
  { id: 'd144', name: '中医推拿科', icon: 'stethoscope' },
  { id: 'd145', name: '皮肤性病科', icon: 'stethoscope' },
  { id: 'd146', name: '医学检验科', icon: 'stethoscope' },
  { id: 'd147', name: '针刀科', icon: 'stethoscope' },
  { id: 'd148', name: '皮肤病科', icon: 'stethoscope' },
  { id: 'd149', name: '特需门诊', icon: 'stethoscope' },
  { id: 'd150', name: '治未病科', icon: 'stethoscope' },
  { id: 'd151', name: '性传播疾病科', icon: 'stethoscope' },
  { id: 'd152', name: '传统医学科', icon: 'stethoscope' },
]

// 常见同义名归一，避免历史数据和新科室库匹配不上
const DEPARTMENT_ALIAS_MAP: Record<string, string> = {
  内科: '普通内科',
  外科: '普通外科',
  普外科: '普通外科',
  心内: '心内科',
  心血管科: '心血管内科',
  儿科: '小儿普通科',
  皮肤科: '皮肤病科',
  皮肤性病: '皮肤性病科',
  耳鼻喉科: '耳鼻喉头颈外科',
  眼科门诊: '眼科',
  口腔: '口腔科',
  康复科: '康复医学科',
  肿瘤: '肿瘤科',
  消化科: '消化内科',
  呼吸科: '呼吸内科',
}

export function normalizeDepartmentName(name: string): string {
  const trimmed = name.trim()
  return DEPARTMENT_ALIAS_MAP[trimmed] || trimmed
}
