/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClerkRouteRouteImport } from './routes/clerk/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as ClerkAuthenticatedRouteRouteImport } from './routes/clerk/_authenticated/route'
import { Route as ClerkauthRouteRouteImport } from './routes/clerk/(auth)/route'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedWorkflowsIndexRouteImport } from './routes/_authenticated/workflows/index'
import { Route as AuthenticatedWithdrawalsIndexRouteImport } from './routes/_authenticated/withdrawals/index'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTagsIndexRouteImport } from './routes/_authenticated/tags/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedServicesIndexRouteImport } from './routes/_authenticated/services/index'
import { Route as AuthenticatedServiceGuaranteesIndexRouteImport } from './routes/_authenticated/service-guarantees/index'
import { Route as AuthenticatedServiceCategoriesIndexRouteImport } from './routes/_authenticated/service-categories/index'
import { Route as AuthenticatedRolesIndexRouteImport } from './routes/_authenticated/roles/index'
import { Route as AuthenticatedPositionsIndexRouteImport } from './routes/_authenticated/positions/index'
import { Route as AuthenticatedOrdersIndexRouteImport } from './routes/_authenticated/orders/index'
import { Route as AuthenticatedOrderSettingsIndexRouteImport } from './routes/_authenticated/order-settings/index'
import { Route as AuthenticatedOperationGuidesIndexRouteImport } from './routes/_authenticated/operation-guides/index'
import { Route as AuthenticatedMedicalTagsIndexRouteImport } from './routes/_authenticated/medical-tags/index'
import { Route as AuthenticatedMedicalLevelsIndexRouteImport } from './routes/_authenticated/medical-levels/index'
import { Route as AuthenticatedHospitalsIndexRouteImport } from './routes/_authenticated/hospitals/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedFilesIndexRouteImport } from './routes/_authenticated/files/index'
import { Route as AuthenticatedEscortsIndexRouteImport } from './routes/_authenticated/escorts/index'
import { Route as AuthenticatedEscortTagsIndexRouteImport } from './routes/_authenticated/escort-tags/index'
import { Route as AuthenticatedEscortLevelsIndexRouteImport } from './routes/_authenticated/escort-levels/index'
import { Route as AuthenticatedEscortCategoriesIndexRouteImport } from './routes/_authenticated/escort-categories/index'
import { Route as AuthenticatedEmployeesIndexRouteImport } from './routes/_authenticated/employees/index'
import { Route as AuthenticatedDoctorsIndexRouteImport } from './routes/_authenticated/doctors/index'
import { Route as AuthenticatedDepartmentsIndexRouteImport } from './routes/_authenticated/departments/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as ClerkAuthenticatedUserManagementRouteImport } from './routes/clerk/_authenticated/user-management'
import { Route as ClerkauthSignUpRouteImport } from './routes/clerk/(auth)/sign-up'
import { Route as ClerkauthSignInRouteImport } from './routes/clerk/(auth)/sign-in'
import { Route as AuthenticatedWithdrawalsSettingsRouteImport } from './routes/_authenticated/withdrawals/settings'
import { Route as AuthenticatedUsersPatientsRouteImport } from './routes/_authenticated/users/patients'
import { Route as AuthenticatedUsersUserIdRouteImport } from './routes/_authenticated/users/$userId'
import { Route as AuthenticatedSupportReviewsRouteImport } from './routes/_authenticated/support/reviews'
import { Route as AuthenticatedSupportQuickRepliesRouteImport } from './routes/_authenticated/support/quick-replies'
import { Route as AuthenticatedSupportFeedbackRouteImport } from './routes/_authenticated/support/feedback'
import { Route as AuthenticatedSupportChatRouteImport } from './routes/_authenticated/support/chat'
import { Route as AuthenticatedSettingsSmsRouteImport } from './routes/_authenticated/settings/sms'
import { Route as AuthenticatedSettingsPaymentRouteImport } from './routes/_authenticated/settings/payment'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsMiniappRouteImport } from './routes/_authenticated/settings/miniapp'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedServicesIdRouteImport } from './routes/_authenticated/services/$id'
import { Route as AuthenticatedFinanceTransactionsRouteImport } from './routes/_authenticated/finance/transactions'
import { Route as AuthenticatedFinanceSettlementsRouteImport } from './routes/_authenticated/finance/settlements'
import { Route as AuthenticatedFinanceInvoicesRouteImport } from './routes/_authenticated/finance/invoices'
import { Route as AuthenticatedFinanceBillsRouteImport } from './routes/_authenticated/finance/bills'
import { Route as AuthenticatedEscortsWithdrawRecordsRouteImport } from './routes/_authenticated/escorts/withdraw-records'
import { Route as AuthenticatedEscortsApplicationsRouteImport } from './routes/_authenticated/escorts/applications'
import { Route as AuthenticatedEscortsEscortIdRouteImport } from './routes/_authenticated/escorts/$escortId'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedDistributionTreeRouteImport } from './routes/_authenticated/distribution/tree'
import { Route as AuthenticatedDistributionSettingsRouteImport } from './routes/_authenticated/distribution/settings'
import { Route as AuthenticatedDistributionRecordsRouteImport } from './routes/_authenticated/distribution/records'
import { Route as AuthenticatedDistributionApplicationsRouteImport } from './routes/_authenticated/distribution/applications'
import { Route as AuthenticatedAppHotKeywordsRouteImport } from './routes/_authenticated/app/hot-keywords'
import { Route as AuthenticatedAppBannersRouteImport } from './routes/_authenticated/app/banners'
import { Route as AuthenticatedMarketingSettingsIndexRouteImport } from './routes/_authenticated/marketing/settings/index'
import { Route as AuthenticatedMarketingPricingIndexRouteImport } from './routes/_authenticated/marketing/pricing/index'
import { Route as AuthenticatedMarketingPointsIndexRouteImport } from './routes/_authenticated/marketing/points/index'
import { Route as AuthenticatedMarketingMembershipIndexRouteImport } from './routes/_authenticated/marketing/membership/index'
import { Route as AuthenticatedMarketingCouponsIndexRouteImport } from './routes/_authenticated/marketing/coupons/index'
import { Route as AuthenticatedMarketingCampaignsIndexRouteImport } from './routes/_authenticated/marketing/campaigns/index'
import { Route as AuthenticatedCmsSidebarsIndexRouteImport } from './routes/_authenticated/cms/sidebars/index'
import { Route as AuthenticatedCmsSettingsIndexRouteImport } from './routes/_authenticated/cms/settings/index'
import { Route as AuthenticatedCmsPagesIndexRouteImport } from './routes/_authenticated/cms/pages/index'
import { Route as AuthenticatedCmsMenusIndexRouteImport } from './routes/_authenticated/cms/menus/index'
import { Route as AuthenticatedCmsArticlesIndexRouteImport } from './routes/_authenticated/cms/articles/index'
import { Route as AuthenticatedCmsArticleTagsIndexRouteImport } from './routes/_authenticated/cms/article-tags/index'
import { Route as AuthenticatedCmsArticleCategoriesIndexRouteImport } from './routes/_authenticated/cms/article-categories/index'
import { Route as AuthenticatedCmsSidebarsNewRouteImport } from './routes/_authenticated/cms/sidebars/new'
import { Route as AuthenticatedCmsSidebarsIdRouteImport } from './routes/_authenticated/cms/sidebars/$id'
import { Route as AuthenticatedCmsPagesIdRouteImport } from './routes/_authenticated/cms/pages/$id'
import { Route as AuthenticatedCmsArticlesIdRouteImport } from './routes/_authenticated/cms/articles/$id'
import { Route as AuthenticatedAppSettingsHomepageRouteImport } from './routes/_authenticated/app/settings/homepage'
import { Route as AuthenticatedAppSettingsBrandRouteImport } from './routes/_authenticated/app/settings/brand'

const ClerkRouteRoute = ClerkRouteRouteImport.update({
  id: '/clerk',
  path: '/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkAuthenticatedRouteRoute = ClerkAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const ClerkauthRouteRoute = ClerkauthRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkflowsIndexRoute =
  AuthenticatedWorkflowsIndexRouteImport.update({
    id: '/workflows/',
    path: '/workflows/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWithdrawalsIndexRoute =
  AuthenticatedWithdrawalsIndexRouteImport.update({
    id: '/withdrawals/',
    path: '/withdrawals/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTagsIndexRoute = AuthenticatedTagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedServicesIndexRoute =
  AuthenticatedServicesIndexRouteImport.update({
    id: '/services/',
    path: '/services/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedServiceGuaranteesIndexRoute =
  AuthenticatedServiceGuaranteesIndexRouteImport.update({
    id: '/service-guarantees/',
    path: '/service-guarantees/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedServiceCategoriesIndexRoute =
  AuthenticatedServiceCategoriesIndexRouteImport.update({
    id: '/service-categories/',
    path: '/service-categories/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRolesIndexRoute = AuthenticatedRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPositionsIndexRoute =
  AuthenticatedPositionsIndexRouteImport.update({
    id: '/positions/',
    path: '/positions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersIndexRoute =
  AuthenticatedOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrderSettingsIndexRoute =
  AuthenticatedOrderSettingsIndexRouteImport.update({
    id: '/order-settings/',
    path: '/order-settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperationGuidesIndexRoute =
  AuthenticatedOperationGuidesIndexRouteImport.update({
    id: '/operation-guides/',
    path: '/operation-guides/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMedicalTagsIndexRoute =
  AuthenticatedMedicalTagsIndexRouteImport.update({
    id: '/medical-tags/',
    path: '/medical-tags/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMedicalLevelsIndexRoute =
  AuthenticatedMedicalLevelsIndexRouteImport.update({
    id: '/medical-levels/',
    path: '/medical-levels/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHospitalsIndexRoute =
  AuthenticatedHospitalsIndexRouteImport.update({
    id: '/hospitals/',
    path: '/hospitals/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFilesIndexRoute = AuthenticatedFilesIndexRouteImport.update({
  id: '/files/',
  path: '/files/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEscortsIndexRoute =
  AuthenticatedEscortsIndexRouteImport.update({
    id: '/escorts/',
    path: '/escorts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEscortTagsIndexRoute =
  AuthenticatedEscortTagsIndexRouteImport.update({
    id: '/escort-tags/',
    path: '/escort-tags/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEscortLevelsIndexRoute =
  AuthenticatedEscortLevelsIndexRouteImport.update({
    id: '/escort-levels/',
    path: '/escort-levels/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEscortCategoriesIndexRoute =
  AuthenticatedEscortCategoriesIndexRouteImport.update({
    id: '/escort-categories/',
    path: '/escort-categories/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployeesIndexRoute =
  AuthenticatedEmployeesIndexRouteImport.update({
    id: '/employees/',
    path: '/employees/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDoctorsIndexRoute =
  AuthenticatedDoctorsIndexRouteImport.update({
    id: '/doctors/',
    path: '/doctors/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDepartmentsIndexRoute =
  AuthenticatedDepartmentsIndexRouteImport.update({
    id: '/departments/',
    path: '/departments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ClerkAuthenticatedUserManagementRoute =
  ClerkAuthenticatedUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => ClerkAuthenticatedRouteRoute,
  } as any)
const ClerkauthSignUpRoute = ClerkauthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const ClerkauthSignInRoute = ClerkauthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const AuthenticatedWithdrawalsSettingsRoute =
  AuthenticatedWithdrawalsSettingsRouteImport.update({
    id: '/withdrawals/settings',
    path: '/withdrawals/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersPatientsRoute =
  AuthenticatedUsersPatientsRouteImport.update({
    id: '/users/patients',
    path: '/users/patients',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersUserIdRoute =
  AuthenticatedUsersUserIdRouteImport.update({
    id: '/users/$userId',
    path: '/users/$userId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupportReviewsRoute =
  AuthenticatedSupportReviewsRouteImport.update({
    id: '/support/reviews',
    path: '/support/reviews',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupportQuickRepliesRoute =
  AuthenticatedSupportQuickRepliesRouteImport.update({
    id: '/support/quick-replies',
    path: '/support/quick-replies',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupportFeedbackRoute =
  AuthenticatedSupportFeedbackRouteImport.update({
    id: '/support/feedback',
    path: '/support/feedback',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupportChatRoute =
  AuthenticatedSupportChatRouteImport.update({
    id: '/support/chat',
    path: '/support/chat',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsSmsRoute =
  AuthenticatedSettingsSmsRouteImport.update({
    id: '/sms',
    path: '/sms',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsPaymentRoute =
  AuthenticatedSettingsPaymentRouteImport.update({
    id: '/payment',
    path: '/payment',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsMiniappRoute =
  AuthenticatedSettingsMiniappRouteImport.update({
    id: '/miniapp',
    path: '/miniapp',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedServicesIdRoute = AuthenticatedServicesIdRouteImport.update({
  id: '/services/$id',
  path: '/services/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceTransactionsRoute =
  AuthenticatedFinanceTransactionsRouteImport.update({
    id: '/finance/transactions',
    path: '/finance/transactions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceSettlementsRoute =
  AuthenticatedFinanceSettlementsRouteImport.update({
    id: '/finance/settlements',
    path: '/finance/settlements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceInvoicesRoute =
  AuthenticatedFinanceInvoicesRouteImport.update({
    id: '/finance/invoices',
    path: '/finance/invoices',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceBillsRoute =
  AuthenticatedFinanceBillsRouteImport.update({
    id: '/finance/bills',
    path: '/finance/bills',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEscortsWithdrawRecordsRoute =
  AuthenticatedEscortsWithdrawRecordsRouteImport.update({
    id: '/escorts/withdraw-records',
    path: '/escorts/withdraw-records',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEscortsApplicationsRoute =
  AuthenticatedEscortsApplicationsRouteImport.update({
    id: '/escorts/applications',
    path: '/escorts/applications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEscortsEscortIdRoute =
  AuthenticatedEscortsEscortIdRouteImport.update({
    id: '/escorts/$escortId',
    path: '/escorts/$escortId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDistributionTreeRoute =
  AuthenticatedDistributionTreeRouteImport.update({
    id: '/distribution/tree',
    path: '/distribution/tree',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDistributionSettingsRoute =
  AuthenticatedDistributionSettingsRouteImport.update({
    id: '/distribution/settings',
    path: '/distribution/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDistributionRecordsRoute =
  AuthenticatedDistributionRecordsRouteImport.update({
    id: '/distribution/records',
    path: '/distribution/records',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDistributionApplicationsRoute =
  AuthenticatedDistributionApplicationsRouteImport.update({
    id: '/distribution/applications',
    path: '/distribution/applications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppHotKeywordsRoute =
  AuthenticatedAppHotKeywordsRouteImport.update({
    id: '/app/hot-keywords',
    path: '/app/hot-keywords',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppBannersRoute = AuthenticatedAppBannersRouteImport.update({
  id: '/app/banners',
  path: '/app/banners',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketingSettingsIndexRoute =
  AuthenticatedMarketingSettingsIndexRouteImport.update({
    id: '/marketing/settings/',
    path: '/marketing/settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMarketingPricingIndexRoute =
  AuthenticatedMarketingPricingIndexRouteImport.update({
    id: '/marketing/pricing/',
    path: '/marketing/pricing/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMarketingPointsIndexRoute =
  AuthenticatedMarketingPointsIndexRouteImport.update({
    id: '/marketing/points/',
    path: '/marketing/points/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMarketingMembershipIndexRoute =
  AuthenticatedMarketingMembershipIndexRouteImport.update({
    id: '/marketing/membership/',
    path: '/marketing/membership/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMarketingCouponsIndexRoute =
  AuthenticatedMarketingCouponsIndexRouteImport.update({
    id: '/marketing/coupons/',
    path: '/marketing/coupons/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMarketingCampaignsIndexRoute =
  AuthenticatedMarketingCampaignsIndexRouteImport.update({
    id: '/marketing/campaigns/',
    path: '/marketing/campaigns/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCmsSidebarsIndexRoute =
  AuthenticatedCmsSidebarsIndexRouteImport.update({
    id: '/cms/sidebars/',
    path: '/cms/sidebars/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCmsSettingsIndexRoute =
  AuthenticatedCmsSettingsIndexRouteImport.update({
    id: '/cms/settings/',
    path: '/cms/settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCmsPagesIndexRoute =
  AuthenticatedCmsPagesIndexRouteImport.update({
    id: '/cms/pages/',
    path: '/cms/pages/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCmsMenusIndexRoute =
  AuthenticatedCmsMenusIndexRouteImport.update({
    id: '/cms/menus/',
    path: '/cms/menus/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCmsArticlesIndexRoute =
  AuthenticatedCmsArticlesIndexRouteImport.update({
    id: '/cms/articles/',
    path: '/cms/articles/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCmsArticleTagsIndexRoute =
  AuthenticatedCmsArticleTagsIndexRouteImport.update({
    id: '/cms/article-tags/',
    path: '/cms/article-tags/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCmsArticleCategoriesIndexRoute =
  AuthenticatedCmsArticleCategoriesIndexRouteImport.update({
    id: '/cms/article-categories/',
    path: '/cms/article-categories/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCmsSidebarsNewRoute =
  AuthenticatedCmsSidebarsNewRouteImport.update({
    id: '/cms/sidebars/new',
    path: '/cms/sidebars/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCmsSidebarsIdRoute =
  AuthenticatedCmsSidebarsIdRouteImport.update({
    id: '/cms/sidebars/$id',
    path: '/cms/sidebars/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCmsPagesIdRoute = AuthenticatedCmsPagesIdRouteImport.update({
  id: '/cms/pages/$id',
  path: '/cms/pages/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCmsArticlesIdRoute =
  AuthenticatedCmsArticlesIdRouteImport.update({
    id: '/cms/articles/$id',
    path: '/cms/articles/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppSettingsHomepageRoute =
  AuthenticatedAppSettingsHomepageRouteImport.update({
    id: '/app/settings/homepage',
    path: '/app/settings/homepage',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppSettingsBrandRoute =
  AuthenticatedAppSettingsBrandRouteImport.update({
    id: '/app/settings/brand',
    path: '/app/settings/brand',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/app/banners': typeof AuthenticatedAppBannersRoute
  '/app/hot-keywords': typeof AuthenticatedAppHotKeywordsRoute
  '/distribution/applications': typeof AuthenticatedDistributionApplicationsRoute
  '/distribution/records': typeof AuthenticatedDistributionRecordsRoute
  '/distribution/settings': typeof AuthenticatedDistributionSettingsRoute
  '/distribution/tree': typeof AuthenticatedDistributionTreeRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/escorts/$escortId': typeof AuthenticatedEscortsEscortIdRoute
  '/escorts/applications': typeof AuthenticatedEscortsApplicationsRoute
  '/escorts/withdraw-records': typeof AuthenticatedEscortsWithdrawRecordsRoute
  '/finance/bills': typeof AuthenticatedFinanceBillsRoute
  '/finance/invoices': typeof AuthenticatedFinanceInvoicesRoute
  '/finance/settlements': typeof AuthenticatedFinanceSettlementsRoute
  '/finance/transactions': typeof AuthenticatedFinanceTransactionsRoute
  '/services/$id': typeof AuthenticatedServicesIdRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/miniapp': typeof AuthenticatedSettingsMiniappRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/payment': typeof AuthenticatedSettingsPaymentRoute
  '/settings/sms': typeof AuthenticatedSettingsSmsRoute
  '/support/chat': typeof AuthenticatedSupportChatRoute
  '/support/feedback': typeof AuthenticatedSupportFeedbackRoute
  '/support/quick-replies': typeof AuthenticatedSupportQuickRepliesRoute
  '/support/reviews': typeof AuthenticatedSupportReviewsRoute
  '/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/users/patients': typeof AuthenticatedUsersPatientsRoute
  '/withdrawals/settings': typeof AuthenticatedWithdrawalsSettingsRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/departments': typeof AuthenticatedDepartmentsIndexRoute
  '/doctors': typeof AuthenticatedDoctorsIndexRoute
  '/employees': typeof AuthenticatedEmployeesIndexRoute
  '/escort-categories': typeof AuthenticatedEscortCategoriesIndexRoute
  '/escort-levels': typeof AuthenticatedEscortLevelsIndexRoute
  '/escort-tags': typeof AuthenticatedEscortTagsIndexRoute
  '/escorts': typeof AuthenticatedEscortsIndexRoute
  '/files': typeof AuthenticatedFilesIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/hospitals': typeof AuthenticatedHospitalsIndexRoute
  '/medical-levels': typeof AuthenticatedMedicalLevelsIndexRoute
  '/medical-tags': typeof AuthenticatedMedicalTagsIndexRoute
  '/operation-guides': typeof AuthenticatedOperationGuidesIndexRoute
  '/order-settings': typeof AuthenticatedOrderSettingsIndexRoute
  '/orders': typeof AuthenticatedOrdersIndexRoute
  '/positions': typeof AuthenticatedPositionsIndexRoute
  '/roles': typeof AuthenticatedRolesIndexRoute
  '/service-categories': typeof AuthenticatedServiceCategoriesIndexRoute
  '/service-guarantees': typeof AuthenticatedServiceGuaranteesIndexRoute
  '/services': typeof AuthenticatedServicesIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/tags': typeof AuthenticatedTagsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/withdrawals': typeof AuthenticatedWithdrawalsIndexRoute
  '/workflows': typeof AuthenticatedWorkflowsIndexRoute
  '/app/settings/brand': typeof AuthenticatedAppSettingsBrandRoute
  '/app/settings/homepage': typeof AuthenticatedAppSettingsHomepageRoute
  '/cms/articles/$id': typeof AuthenticatedCmsArticlesIdRoute
  '/cms/pages/$id': typeof AuthenticatedCmsPagesIdRoute
  '/cms/sidebars/$id': typeof AuthenticatedCmsSidebarsIdRoute
  '/cms/sidebars/new': typeof AuthenticatedCmsSidebarsNewRoute
  '/cms/article-categories': typeof AuthenticatedCmsArticleCategoriesIndexRoute
  '/cms/article-tags': typeof AuthenticatedCmsArticleTagsIndexRoute
  '/cms/articles': typeof AuthenticatedCmsArticlesIndexRoute
  '/cms/menus': typeof AuthenticatedCmsMenusIndexRoute
  '/cms/pages': typeof AuthenticatedCmsPagesIndexRoute
  '/cms/settings': typeof AuthenticatedCmsSettingsIndexRoute
  '/cms/sidebars': typeof AuthenticatedCmsSidebarsIndexRoute
  '/marketing/campaigns': typeof AuthenticatedMarketingCampaignsIndexRoute
  '/marketing/coupons': typeof AuthenticatedMarketingCouponsIndexRoute
  '/marketing/membership': typeof AuthenticatedMarketingMembershipIndexRoute
  '/marketing/points': typeof AuthenticatedMarketingPointsIndexRoute
  '/marketing/pricing': typeof AuthenticatedMarketingPricingIndexRoute
  '/marketing/settings': typeof AuthenticatedMarketingSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/app/banners': typeof AuthenticatedAppBannersRoute
  '/app/hot-keywords': typeof AuthenticatedAppHotKeywordsRoute
  '/distribution/applications': typeof AuthenticatedDistributionApplicationsRoute
  '/distribution/records': typeof AuthenticatedDistributionRecordsRoute
  '/distribution/settings': typeof AuthenticatedDistributionSettingsRoute
  '/distribution/tree': typeof AuthenticatedDistributionTreeRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/escorts/$escortId': typeof AuthenticatedEscortsEscortIdRoute
  '/escorts/applications': typeof AuthenticatedEscortsApplicationsRoute
  '/escorts/withdraw-records': typeof AuthenticatedEscortsWithdrawRecordsRoute
  '/finance/bills': typeof AuthenticatedFinanceBillsRoute
  '/finance/invoices': typeof AuthenticatedFinanceInvoicesRoute
  '/finance/settlements': typeof AuthenticatedFinanceSettlementsRoute
  '/finance/transactions': typeof AuthenticatedFinanceTransactionsRoute
  '/services/$id': typeof AuthenticatedServicesIdRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/miniapp': typeof AuthenticatedSettingsMiniappRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/payment': typeof AuthenticatedSettingsPaymentRoute
  '/settings/sms': typeof AuthenticatedSettingsSmsRoute
  '/support/chat': typeof AuthenticatedSupportChatRoute
  '/support/feedback': typeof AuthenticatedSupportFeedbackRoute
  '/support/quick-replies': typeof AuthenticatedSupportQuickRepliesRoute
  '/support/reviews': typeof AuthenticatedSupportReviewsRoute
  '/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/users/patients': typeof AuthenticatedUsersPatientsRoute
  '/withdrawals/settings': typeof AuthenticatedWithdrawalsSettingsRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/departments': typeof AuthenticatedDepartmentsIndexRoute
  '/doctors': typeof AuthenticatedDoctorsIndexRoute
  '/employees': typeof AuthenticatedEmployeesIndexRoute
  '/escort-categories': typeof AuthenticatedEscortCategoriesIndexRoute
  '/escort-levels': typeof AuthenticatedEscortLevelsIndexRoute
  '/escort-tags': typeof AuthenticatedEscortTagsIndexRoute
  '/escorts': typeof AuthenticatedEscortsIndexRoute
  '/files': typeof AuthenticatedFilesIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/hospitals': typeof AuthenticatedHospitalsIndexRoute
  '/medical-levels': typeof AuthenticatedMedicalLevelsIndexRoute
  '/medical-tags': typeof AuthenticatedMedicalTagsIndexRoute
  '/operation-guides': typeof AuthenticatedOperationGuidesIndexRoute
  '/order-settings': typeof AuthenticatedOrderSettingsIndexRoute
  '/orders': typeof AuthenticatedOrdersIndexRoute
  '/positions': typeof AuthenticatedPositionsIndexRoute
  '/roles': typeof AuthenticatedRolesIndexRoute
  '/service-categories': typeof AuthenticatedServiceCategoriesIndexRoute
  '/service-guarantees': typeof AuthenticatedServiceGuaranteesIndexRoute
  '/services': typeof AuthenticatedServicesIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/tags': typeof AuthenticatedTagsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/withdrawals': typeof AuthenticatedWithdrawalsIndexRoute
  '/workflows': typeof AuthenticatedWorkflowsIndexRoute
  '/app/settings/brand': typeof AuthenticatedAppSettingsBrandRoute
  '/app/settings/homepage': typeof AuthenticatedAppSettingsHomepageRoute
  '/cms/articles/$id': typeof AuthenticatedCmsArticlesIdRoute
  '/cms/pages/$id': typeof AuthenticatedCmsPagesIdRoute
  '/cms/sidebars/$id': typeof AuthenticatedCmsSidebarsIdRoute
  '/cms/sidebars/new': typeof AuthenticatedCmsSidebarsNewRoute
  '/cms/article-categories': typeof AuthenticatedCmsArticleCategoriesIndexRoute
  '/cms/article-tags': typeof AuthenticatedCmsArticleTagsIndexRoute
  '/cms/articles': typeof AuthenticatedCmsArticlesIndexRoute
  '/cms/menus': typeof AuthenticatedCmsMenusIndexRoute
  '/cms/pages': typeof AuthenticatedCmsPagesIndexRoute
  '/cms/settings': typeof AuthenticatedCmsSettingsIndexRoute
  '/cms/sidebars': typeof AuthenticatedCmsSidebarsIndexRoute
  '/marketing/campaigns': typeof AuthenticatedMarketingCampaignsIndexRoute
  '/marketing/coupons': typeof AuthenticatedMarketingCouponsIndexRoute
  '/marketing/membership': typeof AuthenticatedMarketingMembershipIndexRoute
  '/marketing/points': typeof AuthenticatedMarketingPointsIndexRoute
  '/marketing/pricing': typeof AuthenticatedMarketingPricingIndexRoute
  '/marketing/settings': typeof AuthenticatedMarketingSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/clerk': typeof ClerkRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/clerk/(auth)': typeof ClerkauthRouteRouteWithChildren
  '/clerk/_authenticated': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/app/banners': typeof AuthenticatedAppBannersRoute
  '/_authenticated/app/hot-keywords': typeof AuthenticatedAppHotKeywordsRoute
  '/_authenticated/distribution/applications': typeof AuthenticatedDistributionApplicationsRoute
  '/_authenticated/distribution/records': typeof AuthenticatedDistributionRecordsRoute
  '/_authenticated/distribution/settings': typeof AuthenticatedDistributionSettingsRoute
  '/_authenticated/distribution/tree': typeof AuthenticatedDistributionTreeRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/escorts/$escortId': typeof AuthenticatedEscortsEscortIdRoute
  '/_authenticated/escorts/applications': typeof AuthenticatedEscortsApplicationsRoute
  '/_authenticated/escorts/withdraw-records': typeof AuthenticatedEscortsWithdrawRecordsRoute
  '/_authenticated/finance/bills': typeof AuthenticatedFinanceBillsRoute
  '/_authenticated/finance/invoices': typeof AuthenticatedFinanceInvoicesRoute
  '/_authenticated/finance/settlements': typeof AuthenticatedFinanceSettlementsRoute
  '/_authenticated/finance/transactions': typeof AuthenticatedFinanceTransactionsRoute
  '/_authenticated/services/$id': typeof AuthenticatedServicesIdRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/miniapp': typeof AuthenticatedSettingsMiniappRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/settings/payment': typeof AuthenticatedSettingsPaymentRoute
  '/_authenticated/settings/sms': typeof AuthenticatedSettingsSmsRoute
  '/_authenticated/support/chat': typeof AuthenticatedSupportChatRoute
  '/_authenticated/support/feedback': typeof AuthenticatedSupportFeedbackRoute
  '/_authenticated/support/quick-replies': typeof AuthenticatedSupportQuickRepliesRoute
  '/_authenticated/support/reviews': typeof AuthenticatedSupportReviewsRoute
  '/_authenticated/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/_authenticated/users/patients': typeof AuthenticatedUsersPatientsRoute
  '/_authenticated/withdrawals/settings': typeof AuthenticatedWithdrawalsSettingsRoute
  '/clerk/(auth)/sign-in': typeof ClerkauthSignInRoute
  '/clerk/(auth)/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/_authenticated/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/departments/': typeof AuthenticatedDepartmentsIndexRoute
  '/_authenticated/doctors/': typeof AuthenticatedDoctorsIndexRoute
  '/_authenticated/employees/': typeof AuthenticatedEmployeesIndexRoute
  '/_authenticated/escort-categories/': typeof AuthenticatedEscortCategoriesIndexRoute
  '/_authenticated/escort-levels/': typeof AuthenticatedEscortLevelsIndexRoute
  '/_authenticated/escort-tags/': typeof AuthenticatedEscortTagsIndexRoute
  '/_authenticated/escorts/': typeof AuthenticatedEscortsIndexRoute
  '/_authenticated/files/': typeof AuthenticatedFilesIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/hospitals/': typeof AuthenticatedHospitalsIndexRoute
  '/_authenticated/medical-levels/': typeof AuthenticatedMedicalLevelsIndexRoute
  '/_authenticated/medical-tags/': typeof AuthenticatedMedicalTagsIndexRoute
  '/_authenticated/operation-guides/': typeof AuthenticatedOperationGuidesIndexRoute
  '/_authenticated/order-settings/': typeof AuthenticatedOrderSettingsIndexRoute
  '/_authenticated/orders/': typeof AuthenticatedOrdersIndexRoute
  '/_authenticated/positions/': typeof AuthenticatedPositionsIndexRoute
  '/_authenticated/roles/': typeof AuthenticatedRolesIndexRoute
  '/_authenticated/service-categories/': typeof AuthenticatedServiceCategoriesIndexRoute
  '/_authenticated/service-guarantees/': typeof AuthenticatedServiceGuaranteesIndexRoute
  '/_authenticated/services/': typeof AuthenticatedServicesIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/tags/': typeof AuthenticatedTagsIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/withdrawals/': typeof AuthenticatedWithdrawalsIndexRoute
  '/_authenticated/workflows/': typeof AuthenticatedWorkflowsIndexRoute
  '/_authenticated/app/settings/brand': typeof AuthenticatedAppSettingsBrandRoute
  '/_authenticated/app/settings/homepage': typeof AuthenticatedAppSettingsHomepageRoute
  '/_authenticated/cms/articles/$id': typeof AuthenticatedCmsArticlesIdRoute
  '/_authenticated/cms/pages/$id': typeof AuthenticatedCmsPagesIdRoute
  '/_authenticated/cms/sidebars/$id': typeof AuthenticatedCmsSidebarsIdRoute
  '/_authenticated/cms/sidebars/new': typeof AuthenticatedCmsSidebarsNewRoute
  '/_authenticated/cms/article-categories/': typeof AuthenticatedCmsArticleCategoriesIndexRoute
  '/_authenticated/cms/article-tags/': typeof AuthenticatedCmsArticleTagsIndexRoute
  '/_authenticated/cms/articles/': typeof AuthenticatedCmsArticlesIndexRoute
  '/_authenticated/cms/menus/': typeof AuthenticatedCmsMenusIndexRoute
  '/_authenticated/cms/pages/': typeof AuthenticatedCmsPagesIndexRoute
  '/_authenticated/cms/settings/': typeof AuthenticatedCmsSettingsIndexRoute
  '/_authenticated/cms/sidebars/': typeof AuthenticatedCmsSidebarsIndexRoute
  '/_authenticated/marketing/campaigns/': typeof AuthenticatedMarketingCampaignsIndexRoute
  '/_authenticated/marketing/coupons/': typeof AuthenticatedMarketingCouponsIndexRoute
  '/_authenticated/marketing/membership/': typeof AuthenticatedMarketingMembershipIndexRoute
  '/_authenticated/marketing/points/': typeof AuthenticatedMarketingPointsIndexRoute
  '/_authenticated/marketing/pricing/': typeof AuthenticatedMarketingPricingIndexRoute
  '/_authenticated/marketing/settings/': typeof AuthenticatedMarketingSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/clerk'
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/app/banners'
    | '/app/hot-keywords'
    | '/distribution/applications'
    | '/distribution/records'
    | '/distribution/settings'
    | '/distribution/tree'
    | '/errors/$error'
    | '/escorts/$escortId'
    | '/escorts/applications'
    | '/escorts/withdraw-records'
    | '/finance/bills'
    | '/finance/invoices'
    | '/finance/settlements'
    | '/finance/transactions'
    | '/services/$id'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/miniapp'
    | '/settings/notifications'
    | '/settings/payment'
    | '/settings/sms'
    | '/support/chat'
    | '/support/feedback'
    | '/support/quick-replies'
    | '/support/reviews'
    | '/users/$userId'
    | '/users/patients'
    | '/withdrawals/settings'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/chats'
    | '/departments'
    | '/doctors'
    | '/employees'
    | '/escort-categories'
    | '/escort-levels'
    | '/escort-tags'
    | '/escorts'
    | '/files'
    | '/help-center'
    | '/hospitals'
    | '/medical-levels'
    | '/medical-tags'
    | '/operation-guides'
    | '/order-settings'
    | '/orders'
    | '/positions'
    | '/roles'
    | '/service-categories'
    | '/service-guarantees'
    | '/services'
    | '/settings/'
    | '/tags'
    | '/users'
    | '/withdrawals'
    | '/workflows'
    | '/app/settings/brand'
    | '/app/settings/homepage'
    | '/cms/articles/$id'
    | '/cms/pages/$id'
    | '/cms/sidebars/$id'
    | '/cms/sidebars/new'
    | '/cms/article-categories'
    | '/cms/article-tags'
    | '/cms/articles'
    | '/cms/menus'
    | '/cms/pages'
    | '/cms/settings'
    | '/cms/sidebars'
    | '/marketing/campaigns'
    | '/marketing/coupons'
    | '/marketing/membership'
    | '/marketing/points'
    | '/marketing/pricing'
    | '/marketing/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/clerk'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/app/banners'
    | '/app/hot-keywords'
    | '/distribution/applications'
    | '/distribution/records'
    | '/distribution/settings'
    | '/distribution/tree'
    | '/errors/$error'
    | '/escorts/$escortId'
    | '/escorts/applications'
    | '/escorts/withdraw-records'
    | '/finance/bills'
    | '/finance/invoices'
    | '/finance/settlements'
    | '/finance/transactions'
    | '/services/$id'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/miniapp'
    | '/settings/notifications'
    | '/settings/payment'
    | '/settings/sms'
    | '/support/chat'
    | '/support/feedback'
    | '/support/quick-replies'
    | '/support/reviews'
    | '/users/$userId'
    | '/users/patients'
    | '/withdrawals/settings'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/chats'
    | '/departments'
    | '/doctors'
    | '/employees'
    | '/escort-categories'
    | '/escort-levels'
    | '/escort-tags'
    | '/escorts'
    | '/files'
    | '/help-center'
    | '/hospitals'
    | '/medical-levels'
    | '/medical-tags'
    | '/operation-guides'
    | '/order-settings'
    | '/orders'
    | '/positions'
    | '/roles'
    | '/service-categories'
    | '/service-guarantees'
    | '/services'
    | '/settings'
    | '/tags'
    | '/users'
    | '/withdrawals'
    | '/workflows'
    | '/app/settings/brand'
    | '/app/settings/homepage'
    | '/cms/articles/$id'
    | '/cms/pages/$id'
    | '/cms/sidebars/$id'
    | '/cms/sidebars/new'
    | '/cms/article-categories'
    | '/cms/article-tags'
    | '/cms/articles'
    | '/cms/menus'
    | '/cms/pages'
    | '/cms/settings'
    | '/cms/sidebars'
    | '/marketing/campaigns'
    | '/marketing/coupons'
    | '/marketing/membership'
    | '/marketing/points'
    | '/marketing/pricing'
    | '/marketing/settings'
  id:
    | '__root__'
    | '/_authenticated'
    | '/clerk'
    | '/_authenticated/settings'
    | '/clerk/(auth)'
    | '/clerk/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/app/banners'
    | '/_authenticated/app/hot-keywords'
    | '/_authenticated/distribution/applications'
    | '/_authenticated/distribution/records'
    | '/_authenticated/distribution/settings'
    | '/_authenticated/distribution/tree'
    | '/_authenticated/errors/$error'
    | '/_authenticated/escorts/$escortId'
    | '/_authenticated/escorts/applications'
    | '/_authenticated/escorts/withdraw-records'
    | '/_authenticated/finance/bills'
    | '/_authenticated/finance/invoices'
    | '/_authenticated/finance/settlements'
    | '/_authenticated/finance/transactions'
    | '/_authenticated/services/$id'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/miniapp'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/settings/payment'
    | '/_authenticated/settings/sms'
    | '/_authenticated/support/chat'
    | '/_authenticated/support/feedback'
    | '/_authenticated/support/quick-replies'
    | '/_authenticated/support/reviews'
    | '/_authenticated/users/$userId'
    | '/_authenticated/users/patients'
    | '/_authenticated/withdrawals/settings'
    | '/clerk/(auth)/sign-in'
    | '/clerk/(auth)/sign-up'
    | '/clerk/_authenticated/user-management'
    | '/_authenticated/chats/'
    | '/_authenticated/departments/'
    | '/_authenticated/doctors/'
    | '/_authenticated/employees/'
    | '/_authenticated/escort-categories/'
    | '/_authenticated/escort-levels/'
    | '/_authenticated/escort-tags/'
    | '/_authenticated/escorts/'
    | '/_authenticated/files/'
    | '/_authenticated/help-center/'
    | '/_authenticated/hospitals/'
    | '/_authenticated/medical-levels/'
    | '/_authenticated/medical-tags/'
    | '/_authenticated/operation-guides/'
    | '/_authenticated/order-settings/'
    | '/_authenticated/orders/'
    | '/_authenticated/positions/'
    | '/_authenticated/roles/'
    | '/_authenticated/service-categories/'
    | '/_authenticated/service-guarantees/'
    | '/_authenticated/services/'
    | '/_authenticated/settings/'
    | '/_authenticated/tags/'
    | '/_authenticated/users/'
    | '/_authenticated/withdrawals/'
    | '/_authenticated/workflows/'
    | '/_authenticated/app/settings/brand'
    | '/_authenticated/app/settings/homepage'
    | '/_authenticated/cms/articles/$id'
    | '/_authenticated/cms/pages/$id'
    | '/_authenticated/cms/sidebars/$id'
    | '/_authenticated/cms/sidebars/new'
    | '/_authenticated/cms/article-categories/'
    | '/_authenticated/cms/article-tags/'
    | '/_authenticated/cms/articles/'
    | '/_authenticated/cms/menus/'
    | '/_authenticated/cms/pages/'
    | '/_authenticated/cms/settings/'
    | '/_authenticated/cms/sidebars/'
    | '/_authenticated/marketing/campaigns/'
    | '/_authenticated/marketing/coupons/'
    | '/_authenticated/marketing/membership/'
    | '/_authenticated/marketing/points/'
    | '/_authenticated/marketing/pricing/'
    | '/_authenticated/marketing/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ClerkRouteRoute: typeof ClerkRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/clerk': {
      id: '/clerk'
      path: '/clerk'
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk/_authenticated': {
      id: '/clerk/_authenticated'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkAuthenticatedRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/clerk/(auth)': {
      id: '/clerk/(auth)'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkauthRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workflows/': {
      id: '/_authenticated/workflows/'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof AuthenticatedWorkflowsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/withdrawals/': {
      id: '/_authenticated/withdrawals/'
      path: '/withdrawals'
      fullPath: '/withdrawals'
      preLoaderRoute: typeof AuthenticatedWithdrawalsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tags/': {
      id: '/_authenticated/tags/'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof AuthenticatedTagsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/services/': {
      id: '/_authenticated/services/'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AuthenticatedServicesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/service-guarantees/': {
      id: '/_authenticated/service-guarantees/'
      path: '/service-guarantees'
      fullPath: '/service-guarantees'
      preLoaderRoute: typeof AuthenticatedServiceGuaranteesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/service-categories/': {
      id: '/_authenticated/service-categories/'
      path: '/service-categories'
      fullPath: '/service-categories'
      preLoaderRoute: typeof AuthenticatedServiceCategoriesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roles/': {
      id: '/_authenticated/roles/'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthenticatedRolesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/positions/': {
      id: '/_authenticated/positions/'
      path: '/positions'
      fullPath: '/positions'
      preLoaderRoute: typeof AuthenticatedPositionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/': {
      id: '/_authenticated/orders/'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/order-settings/': {
      id: '/_authenticated/order-settings/'
      path: '/order-settings'
      fullPath: '/order-settings'
      preLoaderRoute: typeof AuthenticatedOrderSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operation-guides/': {
      id: '/_authenticated/operation-guides/'
      path: '/operation-guides'
      fullPath: '/operation-guides'
      preLoaderRoute: typeof AuthenticatedOperationGuidesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/medical-tags/': {
      id: '/_authenticated/medical-tags/'
      path: '/medical-tags'
      fullPath: '/medical-tags'
      preLoaderRoute: typeof AuthenticatedMedicalTagsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/medical-levels/': {
      id: '/_authenticated/medical-levels/'
      path: '/medical-levels'
      fullPath: '/medical-levels'
      preLoaderRoute: typeof AuthenticatedMedicalLevelsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hospitals/': {
      id: '/_authenticated/hospitals/'
      path: '/hospitals'
      fullPath: '/hospitals'
      preLoaderRoute: typeof AuthenticatedHospitalsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/files/': {
      id: '/_authenticated/files/'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof AuthenticatedFilesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/escorts/': {
      id: '/_authenticated/escorts/'
      path: '/escorts'
      fullPath: '/escorts'
      preLoaderRoute: typeof AuthenticatedEscortsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/escort-tags/': {
      id: '/_authenticated/escort-tags/'
      path: '/escort-tags'
      fullPath: '/escort-tags'
      preLoaderRoute: typeof AuthenticatedEscortTagsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/escort-levels/': {
      id: '/_authenticated/escort-levels/'
      path: '/escort-levels'
      fullPath: '/escort-levels'
      preLoaderRoute: typeof AuthenticatedEscortLevelsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/escort-categories/': {
      id: '/_authenticated/escort-categories/'
      path: '/escort-categories'
      fullPath: '/escort-categories'
      preLoaderRoute: typeof AuthenticatedEscortCategoriesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employees/': {
      id: '/_authenticated/employees/'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AuthenticatedEmployeesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/doctors/': {
      id: '/_authenticated/doctors/'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof AuthenticatedDoctorsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/departments/': {
      id: '/_authenticated/departments/'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof AuthenticatedDepartmentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/clerk/_authenticated/user-management': {
      id: '/clerk/_authenticated/user-management'
      path: '/user-management'
      fullPath: '/clerk/user-management'
      preLoaderRoute: typeof ClerkAuthenticatedUserManagementRouteImport
      parentRoute: typeof ClerkAuthenticatedRouteRoute
    }
    '/clerk/(auth)/sign-up': {
      id: '/clerk/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/clerk/sign-up'
      preLoaderRoute: typeof ClerkauthSignUpRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/clerk/(auth)/sign-in': {
      id: '/clerk/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/clerk/sign-in'
      preLoaderRoute: typeof ClerkauthSignInRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/_authenticated/withdrawals/settings': {
      id: '/_authenticated/withdrawals/settings'
      path: '/withdrawals/settings'
      fullPath: '/withdrawals/settings'
      preLoaderRoute: typeof AuthenticatedWithdrawalsSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/patients': {
      id: '/_authenticated/users/patients'
      path: '/users/patients'
      fullPath: '/users/patients'
      preLoaderRoute: typeof AuthenticatedUsersPatientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/$userId': {
      id: '/_authenticated/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AuthenticatedUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support/reviews': {
      id: '/_authenticated/support/reviews'
      path: '/support/reviews'
      fullPath: '/support/reviews'
      preLoaderRoute: typeof AuthenticatedSupportReviewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support/quick-replies': {
      id: '/_authenticated/support/quick-replies'
      path: '/support/quick-replies'
      fullPath: '/support/quick-replies'
      preLoaderRoute: typeof AuthenticatedSupportQuickRepliesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support/feedback': {
      id: '/_authenticated/support/feedback'
      path: '/support/feedback'
      fullPath: '/support/feedback'
      preLoaderRoute: typeof AuthenticatedSupportFeedbackRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support/chat': {
      id: '/_authenticated/support/chat'
      path: '/support/chat'
      fullPath: '/support/chat'
      preLoaderRoute: typeof AuthenticatedSupportChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/sms': {
      id: '/_authenticated/settings/sms'
      path: '/sms'
      fullPath: '/settings/sms'
      preLoaderRoute: typeof AuthenticatedSettingsSmsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/payment': {
      id: '/_authenticated/settings/payment'
      path: '/payment'
      fullPath: '/settings/payment'
      preLoaderRoute: typeof AuthenticatedSettingsPaymentRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/miniapp': {
      id: '/_authenticated/settings/miniapp'
      path: '/miniapp'
      fullPath: '/settings/miniapp'
      preLoaderRoute: typeof AuthenticatedSettingsMiniappRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/services/$id': {
      id: '/_authenticated/services/$id'
      path: '/services/$id'
      fullPath: '/services/$id'
      preLoaderRoute: typeof AuthenticatedServicesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance/transactions': {
      id: '/_authenticated/finance/transactions'
      path: '/finance/transactions'
      fullPath: '/finance/transactions'
      preLoaderRoute: typeof AuthenticatedFinanceTransactionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance/settlements': {
      id: '/_authenticated/finance/settlements'
      path: '/finance/settlements'
      fullPath: '/finance/settlements'
      preLoaderRoute: typeof AuthenticatedFinanceSettlementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance/invoices': {
      id: '/_authenticated/finance/invoices'
      path: '/finance/invoices'
      fullPath: '/finance/invoices'
      preLoaderRoute: typeof AuthenticatedFinanceInvoicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance/bills': {
      id: '/_authenticated/finance/bills'
      path: '/finance/bills'
      fullPath: '/finance/bills'
      preLoaderRoute: typeof AuthenticatedFinanceBillsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/escorts/withdraw-records': {
      id: '/_authenticated/escorts/withdraw-records'
      path: '/escorts/withdraw-records'
      fullPath: '/escorts/withdraw-records'
      preLoaderRoute: typeof AuthenticatedEscortsWithdrawRecordsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/escorts/applications': {
      id: '/_authenticated/escorts/applications'
      path: '/escorts/applications'
      fullPath: '/escorts/applications'
      preLoaderRoute: typeof AuthenticatedEscortsApplicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/escorts/$escortId': {
      id: '/_authenticated/escorts/$escortId'
      path: '/escorts/$escortId'
      fullPath: '/escorts/$escortId'
      preLoaderRoute: typeof AuthenticatedEscortsEscortIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/distribution/tree': {
      id: '/_authenticated/distribution/tree'
      path: '/distribution/tree'
      fullPath: '/distribution/tree'
      preLoaderRoute: typeof AuthenticatedDistributionTreeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/distribution/settings': {
      id: '/_authenticated/distribution/settings'
      path: '/distribution/settings'
      fullPath: '/distribution/settings'
      preLoaderRoute: typeof AuthenticatedDistributionSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/distribution/records': {
      id: '/_authenticated/distribution/records'
      path: '/distribution/records'
      fullPath: '/distribution/records'
      preLoaderRoute: typeof AuthenticatedDistributionRecordsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/distribution/applications': {
      id: '/_authenticated/distribution/applications'
      path: '/distribution/applications'
      fullPath: '/distribution/applications'
      preLoaderRoute: typeof AuthenticatedDistributionApplicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/hot-keywords': {
      id: '/_authenticated/app/hot-keywords'
      path: '/app/hot-keywords'
      fullPath: '/app/hot-keywords'
      preLoaderRoute: typeof AuthenticatedAppHotKeywordsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/banners': {
      id: '/_authenticated/app/banners'
      path: '/app/banners'
      fullPath: '/app/banners'
      preLoaderRoute: typeof AuthenticatedAppBannersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketing/settings/': {
      id: '/_authenticated/marketing/settings/'
      path: '/marketing/settings'
      fullPath: '/marketing/settings'
      preLoaderRoute: typeof AuthenticatedMarketingSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketing/pricing/': {
      id: '/_authenticated/marketing/pricing/'
      path: '/marketing/pricing'
      fullPath: '/marketing/pricing'
      preLoaderRoute: typeof AuthenticatedMarketingPricingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketing/points/': {
      id: '/_authenticated/marketing/points/'
      path: '/marketing/points'
      fullPath: '/marketing/points'
      preLoaderRoute: typeof AuthenticatedMarketingPointsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketing/membership/': {
      id: '/_authenticated/marketing/membership/'
      path: '/marketing/membership'
      fullPath: '/marketing/membership'
      preLoaderRoute: typeof AuthenticatedMarketingMembershipIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketing/coupons/': {
      id: '/_authenticated/marketing/coupons/'
      path: '/marketing/coupons'
      fullPath: '/marketing/coupons'
      preLoaderRoute: typeof AuthenticatedMarketingCouponsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketing/campaigns/': {
      id: '/_authenticated/marketing/campaigns/'
      path: '/marketing/campaigns'
      fullPath: '/marketing/campaigns'
      preLoaderRoute: typeof AuthenticatedMarketingCampaignsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cms/sidebars/': {
      id: '/_authenticated/cms/sidebars/'
      path: '/cms/sidebars'
      fullPath: '/cms/sidebars'
      preLoaderRoute: typeof AuthenticatedCmsSidebarsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cms/settings/': {
      id: '/_authenticated/cms/settings/'
      path: '/cms/settings'
      fullPath: '/cms/settings'
      preLoaderRoute: typeof AuthenticatedCmsSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cms/pages/': {
      id: '/_authenticated/cms/pages/'
      path: '/cms/pages'
      fullPath: '/cms/pages'
      preLoaderRoute: typeof AuthenticatedCmsPagesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cms/menus/': {
      id: '/_authenticated/cms/menus/'
      path: '/cms/menus'
      fullPath: '/cms/menus'
      preLoaderRoute: typeof AuthenticatedCmsMenusIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cms/articles/': {
      id: '/_authenticated/cms/articles/'
      path: '/cms/articles'
      fullPath: '/cms/articles'
      preLoaderRoute: typeof AuthenticatedCmsArticlesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cms/article-tags/': {
      id: '/_authenticated/cms/article-tags/'
      path: '/cms/article-tags'
      fullPath: '/cms/article-tags'
      preLoaderRoute: typeof AuthenticatedCmsArticleTagsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cms/article-categories/': {
      id: '/_authenticated/cms/article-categories/'
      path: '/cms/article-categories'
      fullPath: '/cms/article-categories'
      preLoaderRoute: typeof AuthenticatedCmsArticleCategoriesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cms/sidebars/new': {
      id: '/_authenticated/cms/sidebars/new'
      path: '/cms/sidebars/new'
      fullPath: '/cms/sidebars/new'
      preLoaderRoute: typeof AuthenticatedCmsSidebarsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cms/sidebars/$id': {
      id: '/_authenticated/cms/sidebars/$id'
      path: '/cms/sidebars/$id'
      fullPath: '/cms/sidebars/$id'
      preLoaderRoute: typeof AuthenticatedCmsSidebarsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cms/pages/$id': {
      id: '/_authenticated/cms/pages/$id'
      path: '/cms/pages/$id'
      fullPath: '/cms/pages/$id'
      preLoaderRoute: typeof AuthenticatedCmsPagesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cms/articles/$id': {
      id: '/_authenticated/cms/articles/$id'
      path: '/cms/articles/$id'
      fullPath: '/cms/articles/$id'
      preLoaderRoute: typeof AuthenticatedCmsArticlesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/settings/homepage': {
      id: '/_authenticated/app/settings/homepage'
      path: '/app/settings/homepage'
      fullPath: '/app/settings/homepage'
      preLoaderRoute: typeof AuthenticatedAppSettingsHomepageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/settings/brand': {
      id: '/_authenticated/app/settings/brand'
      path: '/app/settings/brand'
      fullPath: '/app/settings/brand'
      preLoaderRoute: typeof AuthenticatedAppSettingsBrandRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsMiniappRoute: typeof AuthenticatedSettingsMiniappRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsPaymentRoute: typeof AuthenticatedSettingsPaymentRoute
  AuthenticatedSettingsSmsRoute: typeof AuthenticatedSettingsSmsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsMiniappRoute: AuthenticatedSettingsMiniappRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsPaymentRoute: AuthenticatedSettingsPaymentRoute,
    AuthenticatedSettingsSmsRoute: AuthenticatedSettingsSmsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAppBannersRoute: typeof AuthenticatedAppBannersRoute
  AuthenticatedAppHotKeywordsRoute: typeof AuthenticatedAppHotKeywordsRoute
  AuthenticatedDistributionApplicationsRoute: typeof AuthenticatedDistributionApplicationsRoute
  AuthenticatedDistributionRecordsRoute: typeof AuthenticatedDistributionRecordsRoute
  AuthenticatedDistributionSettingsRoute: typeof AuthenticatedDistributionSettingsRoute
  AuthenticatedDistributionTreeRoute: typeof AuthenticatedDistributionTreeRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedEscortsEscortIdRoute: typeof AuthenticatedEscortsEscortIdRoute
  AuthenticatedEscortsApplicationsRoute: typeof AuthenticatedEscortsApplicationsRoute
  AuthenticatedEscortsWithdrawRecordsRoute: typeof AuthenticatedEscortsWithdrawRecordsRoute
  AuthenticatedFinanceBillsRoute: typeof AuthenticatedFinanceBillsRoute
  AuthenticatedFinanceInvoicesRoute: typeof AuthenticatedFinanceInvoicesRoute
  AuthenticatedFinanceSettlementsRoute: typeof AuthenticatedFinanceSettlementsRoute
  AuthenticatedFinanceTransactionsRoute: typeof AuthenticatedFinanceTransactionsRoute
  AuthenticatedServicesIdRoute: typeof AuthenticatedServicesIdRoute
  AuthenticatedSupportChatRoute: typeof AuthenticatedSupportChatRoute
  AuthenticatedSupportFeedbackRoute: typeof AuthenticatedSupportFeedbackRoute
  AuthenticatedSupportQuickRepliesRoute: typeof AuthenticatedSupportQuickRepliesRoute
  AuthenticatedSupportReviewsRoute: typeof AuthenticatedSupportReviewsRoute
  AuthenticatedUsersUserIdRoute: typeof AuthenticatedUsersUserIdRoute
  AuthenticatedUsersPatientsRoute: typeof AuthenticatedUsersPatientsRoute
  AuthenticatedWithdrawalsSettingsRoute: typeof AuthenticatedWithdrawalsSettingsRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedDepartmentsIndexRoute: typeof AuthenticatedDepartmentsIndexRoute
  AuthenticatedDoctorsIndexRoute: typeof AuthenticatedDoctorsIndexRoute
  AuthenticatedEmployeesIndexRoute: typeof AuthenticatedEmployeesIndexRoute
  AuthenticatedEscortCategoriesIndexRoute: typeof AuthenticatedEscortCategoriesIndexRoute
  AuthenticatedEscortLevelsIndexRoute: typeof AuthenticatedEscortLevelsIndexRoute
  AuthenticatedEscortTagsIndexRoute: typeof AuthenticatedEscortTagsIndexRoute
  AuthenticatedEscortsIndexRoute: typeof AuthenticatedEscortsIndexRoute
  AuthenticatedFilesIndexRoute: typeof AuthenticatedFilesIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedHospitalsIndexRoute: typeof AuthenticatedHospitalsIndexRoute
  AuthenticatedMedicalLevelsIndexRoute: typeof AuthenticatedMedicalLevelsIndexRoute
  AuthenticatedMedicalTagsIndexRoute: typeof AuthenticatedMedicalTagsIndexRoute
  AuthenticatedOperationGuidesIndexRoute: typeof AuthenticatedOperationGuidesIndexRoute
  AuthenticatedOrderSettingsIndexRoute: typeof AuthenticatedOrderSettingsIndexRoute
  AuthenticatedOrdersIndexRoute: typeof AuthenticatedOrdersIndexRoute
  AuthenticatedPositionsIndexRoute: typeof AuthenticatedPositionsIndexRoute
  AuthenticatedRolesIndexRoute: typeof AuthenticatedRolesIndexRoute
  AuthenticatedServiceCategoriesIndexRoute: typeof AuthenticatedServiceCategoriesIndexRoute
  AuthenticatedServiceGuaranteesIndexRoute: typeof AuthenticatedServiceGuaranteesIndexRoute
  AuthenticatedServicesIndexRoute: typeof AuthenticatedServicesIndexRoute
  AuthenticatedTagsIndexRoute: typeof AuthenticatedTagsIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedWithdrawalsIndexRoute: typeof AuthenticatedWithdrawalsIndexRoute
  AuthenticatedWorkflowsIndexRoute: typeof AuthenticatedWorkflowsIndexRoute
  AuthenticatedAppSettingsBrandRoute: typeof AuthenticatedAppSettingsBrandRoute
  AuthenticatedAppSettingsHomepageRoute: typeof AuthenticatedAppSettingsHomepageRoute
  AuthenticatedCmsArticlesIdRoute: typeof AuthenticatedCmsArticlesIdRoute
  AuthenticatedCmsPagesIdRoute: typeof AuthenticatedCmsPagesIdRoute
  AuthenticatedCmsSidebarsIdRoute: typeof AuthenticatedCmsSidebarsIdRoute
  AuthenticatedCmsSidebarsNewRoute: typeof AuthenticatedCmsSidebarsNewRoute
  AuthenticatedCmsArticleCategoriesIndexRoute: typeof AuthenticatedCmsArticleCategoriesIndexRoute
  AuthenticatedCmsArticleTagsIndexRoute: typeof AuthenticatedCmsArticleTagsIndexRoute
  AuthenticatedCmsArticlesIndexRoute: typeof AuthenticatedCmsArticlesIndexRoute
  AuthenticatedCmsMenusIndexRoute: typeof AuthenticatedCmsMenusIndexRoute
  AuthenticatedCmsPagesIndexRoute: typeof AuthenticatedCmsPagesIndexRoute
  AuthenticatedCmsSettingsIndexRoute: typeof AuthenticatedCmsSettingsIndexRoute
  AuthenticatedCmsSidebarsIndexRoute: typeof AuthenticatedCmsSidebarsIndexRoute
  AuthenticatedMarketingCampaignsIndexRoute: typeof AuthenticatedMarketingCampaignsIndexRoute
  AuthenticatedMarketingCouponsIndexRoute: typeof AuthenticatedMarketingCouponsIndexRoute
  AuthenticatedMarketingMembershipIndexRoute: typeof AuthenticatedMarketingMembershipIndexRoute
  AuthenticatedMarketingPointsIndexRoute: typeof AuthenticatedMarketingPointsIndexRoute
  AuthenticatedMarketingPricingIndexRoute: typeof AuthenticatedMarketingPricingIndexRoute
  AuthenticatedMarketingSettingsIndexRoute: typeof AuthenticatedMarketingSettingsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAppBannersRoute: AuthenticatedAppBannersRoute,
  AuthenticatedAppHotKeywordsRoute: AuthenticatedAppHotKeywordsRoute,
  AuthenticatedDistributionApplicationsRoute:
    AuthenticatedDistributionApplicationsRoute,
  AuthenticatedDistributionRecordsRoute: AuthenticatedDistributionRecordsRoute,
  AuthenticatedDistributionSettingsRoute:
    AuthenticatedDistributionSettingsRoute,
  AuthenticatedDistributionTreeRoute: AuthenticatedDistributionTreeRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedEscortsEscortIdRoute: AuthenticatedEscortsEscortIdRoute,
  AuthenticatedEscortsApplicationsRoute: AuthenticatedEscortsApplicationsRoute,
  AuthenticatedEscortsWithdrawRecordsRoute:
    AuthenticatedEscortsWithdrawRecordsRoute,
  AuthenticatedFinanceBillsRoute: AuthenticatedFinanceBillsRoute,
  AuthenticatedFinanceInvoicesRoute: AuthenticatedFinanceInvoicesRoute,
  AuthenticatedFinanceSettlementsRoute: AuthenticatedFinanceSettlementsRoute,
  AuthenticatedFinanceTransactionsRoute: AuthenticatedFinanceTransactionsRoute,
  AuthenticatedServicesIdRoute: AuthenticatedServicesIdRoute,
  AuthenticatedSupportChatRoute: AuthenticatedSupportChatRoute,
  AuthenticatedSupportFeedbackRoute: AuthenticatedSupportFeedbackRoute,
  AuthenticatedSupportQuickRepliesRoute: AuthenticatedSupportQuickRepliesRoute,
  AuthenticatedSupportReviewsRoute: AuthenticatedSupportReviewsRoute,
  AuthenticatedUsersUserIdRoute: AuthenticatedUsersUserIdRoute,
  AuthenticatedUsersPatientsRoute: AuthenticatedUsersPatientsRoute,
  AuthenticatedWithdrawalsSettingsRoute: AuthenticatedWithdrawalsSettingsRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedDepartmentsIndexRoute: AuthenticatedDepartmentsIndexRoute,
  AuthenticatedDoctorsIndexRoute: AuthenticatedDoctorsIndexRoute,
  AuthenticatedEmployeesIndexRoute: AuthenticatedEmployeesIndexRoute,
  AuthenticatedEscortCategoriesIndexRoute:
    AuthenticatedEscortCategoriesIndexRoute,
  AuthenticatedEscortLevelsIndexRoute: AuthenticatedEscortLevelsIndexRoute,
  AuthenticatedEscortTagsIndexRoute: AuthenticatedEscortTagsIndexRoute,
  AuthenticatedEscortsIndexRoute: AuthenticatedEscortsIndexRoute,
  AuthenticatedFilesIndexRoute: AuthenticatedFilesIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedHospitalsIndexRoute: AuthenticatedHospitalsIndexRoute,
  AuthenticatedMedicalLevelsIndexRoute: AuthenticatedMedicalLevelsIndexRoute,
  AuthenticatedMedicalTagsIndexRoute: AuthenticatedMedicalTagsIndexRoute,
  AuthenticatedOperationGuidesIndexRoute:
    AuthenticatedOperationGuidesIndexRoute,
  AuthenticatedOrderSettingsIndexRoute: AuthenticatedOrderSettingsIndexRoute,
  AuthenticatedOrdersIndexRoute: AuthenticatedOrdersIndexRoute,
  AuthenticatedPositionsIndexRoute: AuthenticatedPositionsIndexRoute,
  AuthenticatedRolesIndexRoute: AuthenticatedRolesIndexRoute,
  AuthenticatedServiceCategoriesIndexRoute:
    AuthenticatedServiceCategoriesIndexRoute,
  AuthenticatedServiceGuaranteesIndexRoute:
    AuthenticatedServiceGuaranteesIndexRoute,
  AuthenticatedServicesIndexRoute: AuthenticatedServicesIndexRoute,
  AuthenticatedTagsIndexRoute: AuthenticatedTagsIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedWithdrawalsIndexRoute: AuthenticatedWithdrawalsIndexRoute,
  AuthenticatedWorkflowsIndexRoute: AuthenticatedWorkflowsIndexRoute,
  AuthenticatedAppSettingsBrandRoute: AuthenticatedAppSettingsBrandRoute,
  AuthenticatedAppSettingsHomepageRoute: AuthenticatedAppSettingsHomepageRoute,
  AuthenticatedCmsArticlesIdRoute: AuthenticatedCmsArticlesIdRoute,
  AuthenticatedCmsPagesIdRoute: AuthenticatedCmsPagesIdRoute,
  AuthenticatedCmsSidebarsIdRoute: AuthenticatedCmsSidebarsIdRoute,
  AuthenticatedCmsSidebarsNewRoute: AuthenticatedCmsSidebarsNewRoute,
  AuthenticatedCmsArticleCategoriesIndexRoute:
    AuthenticatedCmsArticleCategoriesIndexRoute,
  AuthenticatedCmsArticleTagsIndexRoute: AuthenticatedCmsArticleTagsIndexRoute,
  AuthenticatedCmsArticlesIndexRoute: AuthenticatedCmsArticlesIndexRoute,
  AuthenticatedCmsMenusIndexRoute: AuthenticatedCmsMenusIndexRoute,
  AuthenticatedCmsPagesIndexRoute: AuthenticatedCmsPagesIndexRoute,
  AuthenticatedCmsSettingsIndexRoute: AuthenticatedCmsSettingsIndexRoute,
  AuthenticatedCmsSidebarsIndexRoute: AuthenticatedCmsSidebarsIndexRoute,
  AuthenticatedMarketingCampaignsIndexRoute:
    AuthenticatedMarketingCampaignsIndexRoute,
  AuthenticatedMarketingCouponsIndexRoute:
    AuthenticatedMarketingCouponsIndexRoute,
  AuthenticatedMarketingMembershipIndexRoute:
    AuthenticatedMarketingMembershipIndexRoute,
  AuthenticatedMarketingPointsIndexRoute:
    AuthenticatedMarketingPointsIndexRoute,
  AuthenticatedMarketingPricingIndexRoute:
    AuthenticatedMarketingPricingIndexRoute,
  AuthenticatedMarketingSettingsIndexRoute:
    AuthenticatedMarketingSettingsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ClerkauthRouteRouteChildren {
  ClerkauthSignInRoute: typeof ClerkauthSignInRoute
  ClerkauthSignUpRoute: typeof ClerkauthSignUpRoute
}

const ClerkauthRouteRouteChildren: ClerkauthRouteRouteChildren = {
  ClerkauthSignInRoute: ClerkauthSignInRoute,
  ClerkauthSignUpRoute: ClerkauthSignUpRoute,
}

const ClerkauthRouteRouteWithChildren = ClerkauthRouteRoute._addFileChildren(
  ClerkauthRouteRouteChildren,
)

interface ClerkAuthenticatedRouteRouteChildren {
  ClerkAuthenticatedUserManagementRoute: typeof ClerkAuthenticatedUserManagementRoute
}

const ClerkAuthenticatedRouteRouteChildren: ClerkAuthenticatedRouteRouteChildren =
  {
    ClerkAuthenticatedUserManagementRoute:
      ClerkAuthenticatedUserManagementRoute,
  }

const ClerkAuthenticatedRouteRouteWithChildren =
  ClerkAuthenticatedRouteRoute._addFileChildren(
    ClerkAuthenticatedRouteRouteChildren,
  )

interface ClerkRouteRouteChildren {
  ClerkauthRouteRoute: typeof ClerkauthRouteRouteWithChildren
  ClerkAuthenticatedRouteRoute: typeof ClerkAuthenticatedRouteRouteWithChildren
}

const ClerkRouteRouteChildren: ClerkRouteRouteChildren = {
  ClerkauthRouteRoute: ClerkauthRouteRouteWithChildren,
  ClerkAuthenticatedRouteRoute: ClerkAuthenticatedRouteRouteWithChildren,
}

const ClerkRouteRouteWithChildren = ClerkRouteRoute._addFileChildren(
  ClerkRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ClerkRouteRoute: ClerkRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
